### ISSUE TITLE
i use ngx.location.capture api to get 500M response，the memory of worker process grows to 500M  and  doesn't release  。 

### ISSUE THREAD

**Issue by lidong14** [openresty/lua-nginx-module#1093]
i use ngx.location.capture api to get a 500M file, so the response reaches 500M . when the nginx handling the request ,the  the memory of worker process grows to 1.2G. the request processing successful but the memory of worker process is stable in 554M and  doesn't release。

126589 root    20   0  711m 554m 2672 S      0 14.6   0:03.89 nginx: worker process

i know Never use ngx.location.capture for any subrequests with huge responses! It always tries to buffer everything into memory. but the response size is smaller than 1G. the problem is why the memory doesnot release.

**Comment by hongliang5316** [comment]
@lidong14 Maybe you can use this tools (https://github.com/openresty/stapxx) to debug memory leak issues.

**Comment by agentzh** [comment]
@lidong14 It's a VERY bad idea to use `ngx.location.capture` to fully buffer a big file more than 1MB. This is very inefficient. You should really use a lua-resty-http library based on OpenResty's cosocket API that can do streaming (or non-buffered) processing of such large responses from the remote.

Regarding the memory released to the OS, C library allocators like glibc's usually buffer some of the freed memory for later use instead of returning everything directly to the OS. This is a common optimization. You can try the latest OpenResty 1.11.2.3 release which makes the freeing more aggressive.

**Comment by lidong14** [comment]
@hongliang5316 thanks for your tools, i will try later.
@agentzh At first I  think it was not immediately released，but the process holds the 554M memory for several days and never release 。

**Comment by lidong14** [comment]
@agentzh another question， Is there a way to limit the body size of the response ? 3Q

**Comment by agentzh** [comment]
@lidong14 You can easily limit the response data size with streaming processing. That's why I suggested it to you but you seem to ignore my suggestion.

**Comment by lidong14** [comment]
@agentzh i download the lua-resty-http and use it morning. but find that it was not functional than ngx.location.capture.
(1) i want share all the ngx.var from parent request. when i use ngx.location.capture as subrequest to visit the internal location, it is simple as set "share_all_vars = true". but the lua-resty-http cannot complete.
(2) the  lua-resty-http seems to send a new request. i use it to send a https server and it verify the client. so i need bring the certificate. i cannot find any useful example in https://github.com/pintsized/lua-resty-http#request .

**Comment by agentzh** [comment]
@lidong14 If you are accessing fastcgi, then you'd better rewrite your fastcgi backend with Lua and make Lua serve such huge responses directly. Otherwise you do not have much efficient options here.
