### ISSUE TITLE
ngx.var.proxy_add_x_forwarded_for variable not found

### ISSUE THREAD

**Issue by lyenliang** [openresty/lua-nginx-module#1115]
Is it possible to get access to the embedded variables in [ngx_http_proxy_module](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) module from lua code?

I found that `ngx.var.proxy_host`, `ngx.var.proxy_port`, and `ngx.var.proxy_add_x_forwarded_for` are all `nil` even if they have values in nginx.

**Comment by spacewander** [comment]
`proxy_host` and `proxy_port` are available after `proxy_pass`(`log_by_lua` context) in my side.
I could not get `proxy_add_x_forwarded_for` either. lldb showed me that Nginx could not find this variable from hash buckets.

**Comment by agentzh** [comment]
@lyenliang @spacewander This is because those `proxy_*` variables are defined with the `NGX_HTTP_VAR_NOHASH` flag set in the official nginx core, which prohibits runtime value retrieves by variable names.

In OpenResty, we have custom patches to remove that flag for `$proxy_host` and `$proxy_port`:

https://github.com/openresty/openresty/blob/master/patches/nginx-1.11.2-proxy_host_port_vars.patch

We could do the same to the `$proxy_add_x_forwarded_for` in that patch. Pull requests are very welcome :)

**Comment by spacewander** [comment]
@agentzh 
Since `openresty-1.11.2` is already released, maybe we should patch it to a newer version? For example, `nginx-1.13.x-proxy_vars.patch`.

**Comment by agentzh** [comment]
@spacewander The next formal release of OpenResty will still use the nginx 1.11.2 core since we still need more time to fix all the incompatibilities with newer nginx cores.

**Comment by agentzh** [comment]
@lyenliang Please try the following OpenResty prerelease which makes all these nginx variables visible to the Lua land (BTW, the official nginx team rejected such patches due to reasons that are vague and not very convincing. so we have to keep our nginx patches in OpenResty):

https://openresty.org/download/openresty-1.11.2.5rc0.1.tar.gz

**Comment by lyenliang** [comment]
@agentzh Thank you so much. But because my company has been using openresty `1.9.15.1` in the production environment for many months. I'm afraid that upgrading to `1.11.2.5rc0.1` may cause problems.

**Comment by agentzh** [comment]
That version of OpenResty is very very old and has several known security issues. You should really upgrade.
