### ISSUE TITLE
os.execute调用libwebp出错

### ISSUE THREAD

**Issue by xiaolisheng** [openresty/lua-nginx-module#1177]
我在使用libwebp这个库的时候报错了，直接贴代码：
`location = /demowebp{`
`            default_type 'text/html';`
`            content_by_lua_block{`
`            os.execute("cwebp /root/cwebp_test/1.png -q 80 -o /root/cwebp_test/__1.webp")`
`            }`
 `       }`
这个命令在lua中可以运行，但在ngx_lua中运行报错:
`cannot open input file '/root/cwebp_test/1.png'`
`Error! Could not process file /root/cwebp_test/1.png`
`Error! Cannot read input picture file '/root/cwebp_test/1.png'`
困扰了两天了，求大佬相助。

**Comment by agentzh** [comment]
@xiaolisheng Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your problem, it's very likely due to the fact that the system user account (like `nobody`) that is used to run nginx worker processes have not enough permissions to access your file `/root/cwebp_test/1.png`. It's a shame that your libwebp or its Lua binding fails to provide the detailed error message from the operating system.

**Comment by xiaolisheng** [comment]
OK,谢谢你，问题解决了，是没有设置user的原因导致work_process的用户是nobody。英文不太好，抱歉，怕使用英文不能准确表达我的意思，你给的那个地址是墙外的啊，暂时进不去，改天去看下。

**Comment by agentzh** [comment]
@xiaolisheng That is a mailing list. You don't need to access the mailing list's web UI to subscribe to the list.

**Comment by agentzh** [comment]
@xiaolisheng Read the link I gave you above more carefully, which should be accessible in mainland China. You should be able to do all the operations via emails.

**Comment by agentzh** [comment]
No more Chinese here please. This thread is closed.
