### ISSUE TITLE
Request body not passed to ngx.redirect 307

### ISSUE THREAD

**Issue by mszary** [openresty/lua-nginx-module#1184]
I've noticed a strange behaviour during ngx.redirect 307 for POST requests. I'd like to override the request body, but somehow it gets ignored on its way.

Here's the minimal configuration:

```nginx
location = /a {
    content_by_lua '
        ngx.req.read_body()
        ngx.req.set_body_data("value=new")
        ngx.log(ngx.ERR, ngx.req.get_body_data())
        ngx.redirect("/b", 307)
    ';
}
location = /b {
    content_by_lua '
        ngx.req.read_body()
        ngx.say(ngx.req.get_body_data())
    ';
}
```
When I call:
```bash
curl -d "value=somevalue" -L "http://localhost/a"
```
...strange things happen. This is what's in the log files:

```log
172.19.0.1 - - [10/Nov/2017:14:17:28 +0000]  307 "POST /a HTTP/1.1" 193 "-" "curl/7.54.0" "-" "value=new"
172.19.0.1 - - [10/Nov/2017:14:17:28 +0000]  200 "POST /b HTTP/1.1" 27 "-" "curl/7.54.0" "-" "value=somevalue"

```

As you can see it's nicely overridden on /a, but magically returns back to the original values when redirected to /b. 
Am I doing it wrong? Or is it a bug?

My openresty version:
```bash
nginx version: openresty/1.11.2.5
```

**Comment by agentzh** [comment]
@mszary You misunderstood the behavior of 307. It only asks the client to resend the original request body to a new endpoint, it does not allow the server to push a new request body back to the client and let the client to use it instead of the original request body for the new endpoint. Because the client has no idea that the server changes the request body, it definitely still uses the original request body data.

**Comment by mszary** [comment]
You're absolutely right. Thanks for clarification.
