### ISSUE TITLE
Custom header filter module invalid when use ngx.exec()

### ISSUE THREAD

**Issue by bu540402** [openresty/lua-nginx-module#1199]
I use content_by_lua_file 'ngx.exec(@internal)'.
but find a custom header filter module invalid.
the module add some headers for response.
But now the module is not executed。
Those headers are lost

Who can help me to solve this problem ？？ thx

**Comment by spacewander** [comment]
@bu540402 
`ngx.exec` will trigger an internal redirection to the new location `@internal`. Have you configured the custom header filter module in the new location?

If you consider it as a bug of ngx_lua, we need a minimal case to reproduce the issue. It is also important to show us the debug log of Nginx, so that we could know how the custom header filter module works.

**Comment by bu540402** [comment]
@spacewander 

> Have you configured the custom header filter module in the new location?
Module is configured on server directive.
>we need a minimal case to reproduce the issue
It's need some times.
> It is also important to show us the debug log of Nginx
The debug log didn't show any useful message, there aren't the filter module debug logs in error_log file. so I think the filter is not executed。

**Comment by spacewander** [comment]
Could you add this piece of code in your nginx.conf, and use `curl $your_server_addr/test` to test if the custom header filter module works?
```nginx
location = /test {
       error_page 404 = @internal;
}
```

Like `ngx.exec`, the `error_page` directive also triggger an internal redirection. Since the ngx_lua doesn't know the custom header filter module, there may be two occasion:
1. The custom header filter module doesn't handle internal redirection well.
2. ngx_lua modified some Nginx internal environment while running `ngx.exec`, which is necessary for the custom header filter module.

I am not sure which one is true since I know nothing about the custom header filter module.

**Comment by bu540402** [comment]
@spacewander 
> The custom header filter module doesn't handle internal redirection well.
i find the module exists this bug. it can't handle internal redirecton. Thanks for your help
