### ISSUE TITLE
Handy API for Nginx module calling lua function

### ISSUE THREAD

**Issue by hongzhidao** [openresty/lua-nginx-module#1247]
Hi!

It's complicated to do something like sending HTTP request in NGINX process without relying on 'r' (ngx_http_request_t *). Now, it does well in Lua module, through timer.at + httpc.
The problem is it only works in Lua script written in Nginx config.

Is it possible that we're able to call it in Nginx module?

I think it's common for developers, and it's happy if Lua module introduces similarly API ngx_http_lua_get_stat, or anyone experience?

Thanks.

**Comment by agentzh** [comment]
@hongzhidao Have you checked out those lua-resty-http* libraries contributed by the OpenResty community?

You'll have to rely on OpenResty's cosocket API or subrequest API to avoid blocking the nginx event loop. Everything must use nonblocking I/O and integrate with nginx's event loop for network I/O. Otherwise it's doomed inefficient.

**Comment by agentzh** [comment]
@hongzhidao It's too technically difficult to make it the other way around since `ngx_lua` has its own I/O scheduler.

We do provide C APIs for other 3rd-party nginx C modules to provide new Lua APIs. Take a look at the following nginx C module:

https://github.com/openresty/lua-upstream-nginx-module

**Comment by agentzh** [comment]
@hongzhidao Also, you can create pure C libraries in the form of .so files and call them directly from within Lua via LuaJIT FFI.

**Comment by agentzh** [comment]
@hongzhidao Just be careful about network I/O which must be done via OpenResty's facility otherwise it would be totally blocking.

**Comment by hongzhidao** [comment]
Thank you for your detailed suggestions. 
```
 Also, you can create pure C libraries in the form of .so files and call them directly from within Lua via LuaJIT FFI.
``` 
Yep, I think this's the proper choice.
