### ISSUE TITLE
with ngx_lua, my upstream will be disabled

### ISSUE THREAD

**Issue by nanqinlang** [openresty/lua-nginx-module#1298]
the nginx error log is there : 
```log
[error] 10192#0: *1 connect() failed (111: Connection refused) while connecting to upstream
[warn] 10192#0: *1 upstream server temporarily disabled while connecting to upstream
[error] 10192#0: *1 upstream prematurely closed connection while reading response header from upstream
[warn] 10192#0: *1 upstream server temporarily disabled while reading response header from upstream
[error] 10192#0: *1 no live upstreams while connecting to upstream
```

the ngx_lua code i used is : 
```lua
rewrite_by_lua_block {
    local request = ngx.var.cookie_request
    if (request == nil) then
        return ngx.redirect("/request?url=" .. ngx.var.request_uri)
    end
    local response = ngx.md5("salt" .. ngx.var.remote_addr .. request)
    if (ngx.var.cookie_response ~= response) then
       return ngx.redirect("/request?url=" .. ngx.var.request_uri)
    end
}

location /request {
access_by_lua_block {
    local request = math.random(9999)
    local response = ngx.md5("salt" .. ngx.var.remote_addr .. request)
    ngx.header["Set-Cookie"] = {"request=" .. request, "response=" .. response}
    return ngx.redirect(ngx.var.arg_url)
    }
}
```

the situation is :   
i used the ngx_lua code in my nginx, and when someone access my website, the nginx upstream will be temporarily disabled, but a little time after this access, the upstream seems be restarted.  
anytime i or other client tried to access, the "temporarily disabled" loop will be showed.

**Comment by agentzh** [comment]
@nanqinlang Your nginx.conf is incomplete, lacking key configs for proxy_pass, upstream, and etc. Guessing you have misconfigurations in your proxy_pass target due to the "Connection refused" error. We cannot really help with so little info. But my hunch is silly mistakes in your own nginx.conf configurations.

BTW, please join the openresty-en mailing list for such general usage questions. This place is reserved for real bug reports and patch submissions (if you believe it's a bug, then please provide a minimal and self-contained example that we can easily reproduce the problem on our side). Thanks for your cooperation! Please see https://openresty.org/en/community.html
