### ISSUE TITLE
resty.aes High cpu 

### ISSUE THREAD

**Issue by lanss315425** [openresty/lua-nginx-module#1326]
@leafo @ctrochalakis hello!
   I encountered this problem when I was using the resty.aes stress test.
https://github.com/lanss315425/test/blob/master/cpu2018051901.svg
https://raw.githubusercontent.com/lanss315425/test/master/cpu2018051901.svg

**Comment by agentzh** [comment]
@lanss315425 You are reporting things to the wrong place. This is the lua-nginx-module repo but you are talking about the resty.aes module in the lua-resty-string repo. Also, AES is known to be very expensive in CPU usage. What problem are you referring to here? Trying to get help to optimize OpenSSL? Or to help optimize your own Lua code? The CPU flame graph only shows bottlenecks in your own Lua code, not in ngx_lua nor in resty.aes of lua-resty-string. Am I missing anything here?

I'm closing this issue since it is off topic, apparently. I already suggested you post such general questions to the openresty-en mailing list. Please do that. Do not ignore my suggestions otherwise I would stop replying to you since you won't listen to me anyway...
