### ISSUE TITLE
ngx.redirect changing the browser url - require a function that doesn't change

### ISSUE THREAD

**Issue by raghunath1986** [openresty/lua-nginx-module#1339]
This place is for bug reports and development discussions only. For general questions and
discussions, please join the openresty-en mailing list instead: https://openresty.org/en/community.html

Ensure you have provided the following details while reporting a problem:

* The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, the `ngx_lua` module version,
and your operating system version.
Using Kong API gateway 0.13, not sure about the nginx version.
* A minimal and standalone test case that others can easily run on their side and
reproduce the issue you are seeing.
My requirement is to read the API uri and based on the uri path find the upstream urls and tweak the upstream uri path and make a call to upstream url.

For example : 
API url : http://localhost:8000/genericapis/burner/size/1

lua ngx Logic should be :

1. Read Uri path : /genericapis/burner/size/1

2. Since the call is for burner, upstream url will be to electricals : http://<host:port>/ electricals/burner/size/1

3. I could achieve this by making some string manipulations on URI and calling the upstream url using ngx.redirect("http://<host:port>/electricals/burner/size/1") but when I hit the API url i.e http://localhost:8000/genericapis/burner/size/1 it's redirecting to upstream url, which I don't want. I want the response from upstream url but the api url shouldn't be changed.

Please help me to achieve this.

**Comment by agentzh** [comment]
@raghunath1986 Maybe you should look at the `ngx.exec()` API function instead.

BTW, please join the openresty-en mailing list for such general usage questions. This place is reserved for real bug reports and patch submissions. Thanks for
your cooperation! Please see https://openresty.org/en/community.html

Please read the issue template instead of repeating it in your issue text. Otherwise I still have to repeat it manually for you ;)
