### ISSUE TITLE
Make nginx's `env` directive setting visible to the Lua code inside `init_by_lua*`

### ISSUE THREAD

**Issue by agentzh** [openresty/lua-nginx-module#1340]
The following test is failing right now:

```
=== TEST 1: env directive settings should be visiable to init_by_lua*
--- ONLY
--- main_config
env MyTestSysEnv=hello;
--- http_config
    init_by_lua_block {
        package.loaded.foo = os.getenv("MyTestSysEnv")
    }

--- config
location /t {
    content_by_lua_block {
        ngx.say(package.loaded.foo)
        ngx.say(os.getenv("MyTestSysEnv"))
    }
}
--- request
GET /t
--- response_body
hello
hello
--- no_error_log
[error]
```

**Comment by hongliang5316** [comment]
@agentzh 
hello
what do you think of this pr ? (#1341)

**Comment by dndx** [comment]
@hongliang5316 Hi,

Similar to what @agentzh said in #1341, I think it is better not to contaminate the master process with the environment variable and the memory buffer it allocates when setting `environ`. In fact it seems to me that the change causes master's `environ` to be leaked in the spawned worker as well.

Hooking `os.getenv` with lua-resty-core and C FFI API is much safer.

**Comment by hongliang5316** [comment]
@dndx 
Hello, 
thanks you for your guidance, i have already re-implement lua's function `os.getenv` with FFI, #1341 and https://github.com/openresty/lua-resty-core/pull/197 thanks.

**Comment by hongliang5316** [comment]
@thibaultcha 
That's nothing, i need this feature.
Having multiple prs is a good thing :).

**Comment by spacewander** [comment]
Here are two tricky cases we need to consider:
1. an environment variable is made visible in the new conf, via `env VAR` but not `env VAR=`. Maybe we could get the value from `ngx_os_environ`?
2. an environment variable which is visible in the old conf, but is not longer visible in the new conf. I have not figured out an idea to handle it yet.

Most importantly, we need a way to test if the method works fine during reload. Any ideas?

**Comment by dndx** [comment]
@spacewander 

For 1 I think your proposal is the correct way to do it. For 2, it seems that as long as we always uses `ngx_core_conf_t->env` from the `cf` that is passed to post-configuration function we should be fine? Maybe we will have to save the pointer somewhere in `init_by_lua`'s `_G` but should be doable.

**Comment by agentzh** [comment]
Yeah, it's safer to reference values from `cf` in this phase since we may have 2 parallel versions of config during the config reloading phase. Better avoid using C globals.

**Comment by thibaultcha** [comment]
Had a busy couple of days, but got a chance to circle back on this today. Based on my tests with openresty/lua-resty-core#198,

1. @spacewander this PR handles `env VAR` and `env VAR=`, and retrieves the value from the native `os.getenv` if not found in `ccf->env`. Based on the test suite I wrote there and my own local tests, it seems to work great.
2. @spacewander Based on my tests (locally), changes to the `env` directives are visible to the signaller process, to the master process, and to the new master process when upgrading the binary.

> Most importantly, we need a way to test if the method works fine during reload. Any ideas?

3. There may be a better way, but what if we ran ordered tests combined with HUP reload in the Test::Nginx suite? HUP reload seems to only be enabled via an environment variable based on the Test::Nginx::Socket documentation, but I am sure we can easily add support for this on a per test-suite basis, if it doesn't already exist.

4. It seems to me like the proposal in openresty/lua-resty-core#198 is less invasive, since it fallbacks on `os.getenv` when possible, and reverts the overwrite as soon as we know we are in a worker process for sure, to be polite. It relies on the `__ngx_req` global to be present instead of `process.type` to handle single processes.

Maybe I am overlooking a use-case or other concern that you have in mind. Hope that helps.

**Comment by thibaultcha** [comment]
I added a new test to openresty/lua-resty-core#198 ensuring invocations of the `init_handler` from the lua_shared_dict init code path works as well (since we use the `ngx_cycle` assignment trick), as well as a new test suite `os-get-env-hup.t` which implements the solution I proposed above (ordered tests + HUP reload). I am not sure if a binary upgrade test suite is really necessary?

**Comment by thibaultcha** [comment]
@agentzh @dndx @spacewander I will soon be away for a couple of weeks, and therefore may be slower to address feedback during that time. Is there anything of concern that I could address in those PRs before Friday? Let me know.

**Comment by thibaultcha** [comment]
Any news on this?

**Comment by thibaultcha** [comment]
Ping.

**Comment by sweet-greg** [comment]
Is there a status on this? Env variables would be a great addition!

**Comment by thibaultcha** [comment]
This has now been merged and will be part of the next release candidate for the 1.15 release. Considering this issue resolved and closing it now.
