### ISSUE TITLE
Invoke multiple `access_by_lua_block` blocks

### ISSUE THREAD

**Issue by Willux** [openresty/lua-nginx-module#1364]
To start off this, I am using OpenResty 1.13.6.1 and running `nginx` on the Docker container.

Let's say I have an nginx conf like this:
```
server {
  # stuff goes here...
  access_by_lua_block {
    ngx.log(ngx.WARN, 'test1')
  }

  location /test { 
    access_by_lua_block {
      ngx.log(ngx.WARN, 'test2')
    }
  }
}
```

**The effect**:
Whenever I hit the `/test` endpoint, only `'test2'` gets logged. And when I try any other endpoint, only `'test1'` gets logged.

**The expectation**:
Whenever I hit the `/test` endpoint, I want both `'test1'` and `'test2'` to be logged. Is that is possible?

**Comment by thibaultcha** [comment]
Hi,

No. This is not possible. There are many topics online already describing this behavior (e.g. https://groups.google.com/forum/m/#!topic/openresty-en/0RmRy6Q2DOA). 

Best to reorganize your Lua code differently so that it is called as needed by different block directives. It is usually pretty trivial to do so. 

Cheers,

**Comment by Willux** [comment]
I must've missed the discussions. Thank you for the update.
