### ISSUE TITLE
luajit.h not found

### ISSUE THREAD

**Issue by gfrankliu** [openresty/lua-nginx-module#1405]
I am trying 0.10.14rc1 with latest nginx 1.15 on Centos 7 but get below compilation error:

In file included from lua-nginx-module-0.10.14rc1/src/ngx_http_lua_log.h:12:0,
                 from lua-nginx-module-0.10.14rc1/src/ngx_http_lua_log.c:14:
lua-nginx-module-0.10.14rc1/src/ngx_http_lua_common.h:20:20: fatal error: luajit.h: No such file or directory
 #include <luajit.h>

Last version of lua-nginx-module seems to include <lua.h>. Once I changed this line, it compiles fine.

**Comment by agentzh** [comment]
@gfrankliu We now require the use of LuaJIT in this module. The standard Lua 5.1 interpreter is MUCH slower for almost all nontrivial things and it is quite a burden for us to maintain the legacy APIs for the std Lua 5.1 interpreter. We'll remove support for it completely very soon.

BTW, this module is also (much) faster if you use OpenResty instead of compiling against the stock LuaJIT. Still, using the stock LuaJIT is supported anyway, just slower than OpenResty's LuaJIT version when using this module (there is also some Lua users prefer OpenResty's LuaJIT over the stock LuaJIT for contexts other than nginx and openresty). Even using the stock LuaJIT is MUCH faster than the std Lua 5.1 interpreter.

**Comment by agentzh** [comment]
I just updated the docs to reflect this new change.

**Comment by wenlez** [comment]
Okay, I'll have a look.  
With OpenResty, can I still pick which module/bundle to compile or install?

**Comment by agentzh** [comment]
@wenlez Sure. Just see the output of `./configure --help`. Usually you can use the `./configure --without-xxx` to remove stuff.

**Comment by KeksBeskvitovich** [comment]
On Centos 7:
```
yum install epel-release -y && \
yum install luajit-devel -y && \
ln -s /usr/include/luajit-2.0/luajit.h /usr/include/
```
Then build work fine for me

**Comment by intika** [comment]
This module now requires LuaJIT to build. t's recommended to use the OpenResty releases:

`https://openresty.org/en/download.html`

After build and install use this command to build nginx:

    LUAJIT_LIB=/usr/local/openresty/luajit/lib LUAJIT_INC=/usr/local/openresty/luajit/include/luajit-2.1 ./configure

Add to the other config option that you need
