### ISSUE TITLE
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since 

### ISSUE THREAD

**Issue by mgltech** [openresty/lua-nginx-module#1641]
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /usr/local/NGX/conf/nginx.conf:34
nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'

**Comment by starsz** [comment]
Hello, as the error log said,  lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16).
See commit: https://github.com/openresty/lua-nginx-module/commit/60736e686ac5ca5af9a5bf118cb9bd4a9126cefc

Maybe you can use lua-nginx-module before v0.10.16 or install [lua-resty-core](https://github.com/openresty/lua-resty-core).

It is highly recommended to use OpenResty releases which bundle Nginx, ngx_lua (this module), LuaJIT, as well as other powerful companion Nginx modules and Lua libraries. 
See doc: https://github.com/openresty/lua-nginx-module#installation

**Comment by thibaultcha** [comment]
This is just a warning. You can remove the directive (since it is enabled by default) and get rid of the warning altogether.
