### ISSUE TITLE
Documentation for table.new

### ISSUE THREAD

**Issue by sanjade** [openresty/lua-nginx-module#1858]
I don't seem to find any documentation for `table.new`. I've seen the implementation but where is the actual documentation for this?

Like in,

```
local new_tab = require "table.new"

new_tab(0, 2)
```

What does those parameters`(0, 2)` mean?

**Comment by LubinLew** [comment]
table.new() and table.clear() are LuaJIT-2.1 extensions.
Documentation is in https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/extensions.html

`table.new(narr , nrec ) `
> http://www.lua.org/manual/5.1/manual.html
Creates a new empty table and pushes it onto the stack. The new table has space pre-allocated for `narr` array elements and `nrec `non-array elements. This pre-allocation is useful when you know exactly how many elements the table will have. Otherwise you can use the function

**Comment by sanjade** [comment]
@LubinLew Thanks a lot. That helps. According to the doc it says: `table.new(narray, nhash)`. So let's say I want 4 numbers to be in a table, I should do `table.new(4, 0)` right? And let's say I want 4 keys with their values as a hash, I should do `table.new(0, 4)` right?

**Comment by LubinLew** [comment]
Yes,you‘re right

**Comment by sanjade** [comment]
Thanks a lot
