### ISSUE TITLE
udp sockets in log_by_lua phase

### ISSUE THREAD

**Issue by gringus** [openresty/lua-nginx-module#244]
I see that udp socket related functionality (eg. ngx.socket.udp()) is not available in log_by_lua phase. Is this an omission or limitation ? We have a use case when we want to send some udp based events and log_by_lua phase seems like the right match for that.

**Comment by lilydjwg** [comment]
Thanks you! But Ithink it should be mentioned where `log_by_lua` is documented, since it's not uncommon to send out log data via UDP.

**Comment by agentzh** [comment]
@lilydjwg I think you should always check the "context:" section of the Lua API functions. For example, to quote the documentation for ngx.socket.udp():

> syntax: udpsock = ngx.socket.udp()
> 
> context: rewrite_by_lua*, access_by_lua*, content_by_lua*, ngx.timer.*, ssl_certificate_by_lua*
>

You can see that no `log_by_lua*` is listed in the context section.

See more info at https://github.com/openresty/lua-nginx-module#ngxsocketudp

I don't want to document such things in the documentation of `log_by_lua*` itself, since there's just too many Lua APIs that are disabled in that context.

**Comment by lilydjwg** [comment]
I've checked that, and thought it's not possible. So I googled to see if there is a workaround, then found this.

I always feel the documentation is not very navigatable, and it takes a lot of time to figure out the right thing I need (compared to the nginx documentations). But I don't know why. Maybe you can split them into smaller pages and let Google to navigate readers?

**Comment by agentzh** [comment]
@lilydjwg Yeah, maybe.
