### ISSUE TITLE
Port this module to Lua 5.2

### ISSUE THREAD

**Issue by teward** [openresty/lua-nginx-module#343]
This is marked "high priority" because this impacts the nginx package in Ubuntu.

In order to get `nginx` into Ubuntu main, the Lua module will need to be updated to work with Lua 5.2.  The current 5.1 dependency blocks the package from being acceptable for the process of getting some part of nginx into main.

Unless this module gets ported to 5.2, and relatively soon, the module will have to be dropped in Ubuntu.  It will still exist in the Debian-based nginx packages in the PPAs, but it will not be in the Ubuntu nginx packages unless this gets updated for 5.2.

**Comment by mathieujobin** [comment]
What happened with this ? are we still lock with 5.1 ?
What about 5.3 ?

thanks

**Comment by teward** [comment]
I don't think the state on this has changed...

**Comment by mathieujobin** [comment]
thanks for your answer, so 5.1 it is.

I quickly baked a few bash functions to easily switch lua version on archlinux

in case anyone is interested

https://github.com/mathieujobin/lua_version_manager

**Comment by bungle** [comment]
One of the reasons, as I see it, is that this module supports both LuaJIT 2.1 and PUC-Lua 5.1. And LuaJIT is stuck with Lua 5.1. Making PUC-Lua support for say 5.3 and LuaJIT support for 2.1, you are dividing the community that writes _plain_ Lua modules for this platform. 5.1 and 2.1 are quite compatible with each other, so that does not create a huge amounts of incompatibilities. LuaJIT FFI on the otherhand doesn't work with PUC-Lua, of course. It seems that more effort is put on LuaJIT side, and many of the new features gets implemented with FFI interface. Future tells how PUC-Lua and LuaJIT lives together in this module.
