### ISSUE TITLE
'end' expected (to close 'function' at line 1) near '<eof>'

### ISSUE THREAD

**Issue by kworr** [openresty/lua-nginx-module#385]
When  trying to load a file with a size exactly 4096 bytes nginx fails with this error. Everything works perfectly otherwise.

**Comment by francoispluchino** [comment]
@agentzh I reopen this old issue again because I get exactly the same error when I modify an LUA file and restart the Nginx server. I use the Docker Toolbox with an Alpine Linux OpenResty Fat edition on a Windows Home 10 64 bits for the host machine (latest stable releases for all). All is ok when I restart the virtual machine.

```
proxy    | 2018/02/22 17:31:17 [error] 1#1: init_by_lua error: error loading module 'storage_adapters.postgresql' from file '/var/www/html/.docker/common/proxy/lua_modules/storage_adapters/postgresql.lua':
proxy    |      ...common/proxy/lua_modules/storage_adapters/postgresql.lua:164: '=' expected near '<eof>'
```

Of course, I also have this error when I use a simple LUA file in the `init_by_lua_file` directive.

**Comment by agentzh** [comment]
@francoispluchino I don't think it's related. This original issue was for FreeBSD only, *not* on Linux, if you look closer enough. You need to provide a minimal and standalone example for us to reproduce and investigate. And no docker (we are not responsible to debug docker specific issues anyway).
