### ISSUE TITLE
Bug report  about ngx.location.capture , really hope you can help fix this bug soon , thx !!!!!!!

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [openresty/lua-nginx-module#452]
I am a new githuber ,hope you can follow  me . the nginx-lua-module version is 0.9.13 , then nginx version is 1.5.7

if ngx.location.capture  captured  404  from upstream server ,  the estab connections can not be released,

pmap the nginx worker pid , i can see the pid use more and more mem , and no more release
use bash commad "ss -s" , i can see these is more an more  estab connections 

if ngx.location.capture  captured  200  from upstream server ,  there is no problem
if i use ngx.exec , the same code, upstream server return 200 or 404 , there is no problem

my lua code ：

res = ngx.location.capture(internal_proxy_path,{vars = {upstream_url = ngx.var.upstream_url,  cid = ngx.var.cid} })
-- res = ngx.location.capture(internal_proxy_path)

my nginx  location ：
 location /internal_proxy_live
 {
        internal;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_connect_timeout    10s;
        proxy_read_timeout          10s;
        proxy_send_timeout         10s;
        proxy_set_header Connection "";
        proxy_set_header Accept-Encoding "";
        proxy_cache_use_stale error timeout updating http_502 http_504;
        proxy_cache_lock on;
        proxy_cache_lock_timeout 2s;
        proxy_ignore_headers Cache-Control Expires;
        more_set_headers "X-Cache-Status: $upstream_cache_status";
        more_set_headers "Live: m3u8";
        proxy_cache cache_live;
        proxy_cache_valid  200 304 5s;
        proxy_cache_key  $cid;
        proxy_pass  $upstream_url;
        log_by_lua_file     lua/cdn/common/hls_sub_log.lua;
 }

my test.sh 
#!/bin/bash
for i in `seq 360000`
do
    for j in `seq 20`
    do
        curl -i " a url  " &
    done
    sleep 1
done

the curl  return ：

Server: ZXC-Server
Date: Wed, 21 Jan 2015 03:02:46 GMT
Content-Type: text/html
Content-Length: 162
Connection: close

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by zhengxiaochuan-3** [comment]
any response ?!

**Comment by agentzh** [comment]
@zhengxiaochuan-3 Please provide a minimal and standalone example that I can directly run on my side. Please try removing as much things as possible, as long as the problem still persists. Also, please re-format your message properly, for example, the code snippets shown above are really messy when displayed by the github website.

One common cause for your issue is that your backend server sends an incorrect Content-Length response header value. Ensure the actual response body size is exactly equal to the size that the Content-Length response header announces. If the former is smaller than the latter (even only by 1 byte), then nginx just keeps waiting for more data on the connection, leading to ESTABLISHED backend connections hanging for long (until the default 60s timeout is reached).

I know English is not your first language. You can consider posting in Chinese on the openresty (Chinese) mailing list instead. See http://openresty.org/#Community

**Comment by agentzh** [comment]
@zhengxiaochuan-3 BTW, the `proxy_cache_lock` thing in older nginx cores (including 1.5.7) is known to have issues in subrequests (initiated by `ngx.location.capture`, for example), which can lead to request hang.

Please try upgrading the nginx core to the latest version or just use the latest OpenResty release instead:

http://openresty.org/#Download

**Comment by zhengxiaochuan-3** [comment]
Thank you , it is indeed the "proxy_cache_lock" issue , i just close the cache_lock, all things goes well

and i will try to use openresty instead nginx.

**Comment by agentzh** [comment]
@zhengxiaochuan-3 Glad to hear that :) I'm closing this ticket.

**Comment by zhengxiaochuan-3** [comment]
章大神，看到你新浪微博说你用内存泄漏火焰图工具快速定位了一个和网络视频相关的nginx c的内存泄漏问题   我这边好像也发现在播放大文件视频 比如mp4时 (非hls的)  确实有内存泄漏  困扰了很久   ，请问你🈶什么解决办法吗？ 或者能不能帮忙描述下这个bug？  十分感谢！

发自我的 iPhone

**Comment by agentzh** [comment]
@zhengxiaochuan-3 No Chinese here. Thank you. Also your comment is completely off-topic for this ticket, which is very bad.
