### ISSUE TITLE
Catch the event of "Connection Lost" or detect "Half-open TCP Connection" ?

### ISSUE THREAD

**Issue by hanfeisun** [openresty/lua-nginx-module#454]
I'm using `lua-nginx-module-0.9.13` and `lua-resty-logger-socket` to serve HLS streaming videos.. When the connection is lost, for example, when Flash video players crashes, I want the nginx server to make a HTTP request to another server..

However, I didn't find a way to catch the event of `Connection Lost` and run a function when the event of `Connection Lost` is triggered..

**Comment by agentzh** [comment]
@hanfeisun I'm confused. Are you talking about downstream connections or upstream connections?

For downstream connections, please check out the `ngx.on_abort` API provided by ngx_lua (BTW, `lua-resty-logger-socket` should not be used for this since it uses an async timer under the hood. you should use the cosocket API directly in the request handler context).

For upstream connections, you can just handle the "close" errors with your cosocket operations yourself in Lua. Yeah, another reason to use the cosocket API directly.

**Comment by agentzh** [comment]
@hanfeisun For half-open TCP connections, you'll have to enable the "TCP keepalive" feature in your OS kernel's TCP stack. This is also documented in `lua_check_client_abort` API's official documentation:

https://github.com/openresty/lua-nginx-module#lua_check_client_abort

**Comment by hanfeisun** [comment]
My question seems a duplicate of https://github.com/openresty/lua-nginx-module/issues/455

If the handling could only be done from outside, maybe this issue can be closed...

**Comment by agentzh** [comment]
I didn't know they are of the same context. Then you should follow my
suggestions in #445.

BTW, please always be more specific when asking a question or it's easy to
misinterpreted your intention. In addition, please don't cross-post. It's
annoying. Thank you for your cooperation.

**Comment by agentzh** [comment]
Consider it resolved.
