### ISSUE TITLE
Incorrect upstream_response_time after ngx.exit()

### ISSUE THREAD

**Issue by danielfbento** [openresty/lua-nginx-module#457]
Hello,

We are using the lua-nginx-module for a couple of things and we faced a problem with some type of race condition which we don't understand very well.

We have a sample location (with a proxy_pass) where we do:

    header_filter_by_lua_file 'script.lua' 

which has the following code:

    ngx.log(ngx.WARN, string.format("script.lua"))
    ngx.exit(582)

we also have a named location to catch this 582 error

    error_page 582 @error_582 

where we return to the client a 302 Status Code.

If we benchmark this configuration, sometimes (it's not clear why), in the uptream_response_time we have a timestamp instead of the time used to the upstream. We couldn't figure why this happen and if it is caused by a specific situation.

For a simple concurrency test, we put the call *ngx.sleep(0.001)* before the *ngx.exit()* call. We never get back the timestamp in the logs but always the right value.

    ngx.sleep(0.001)
    ngx.exit(582)

Can this be a problem of the lua-nginx-module?

Thanks

**Comment by agentzh** [comment]
@danielfbento Thanks for the report! I can reproduce the issue locally with `ab`. The bad samples are approximately 5 out of 7000 requests. I'll investigate the root cause for this. It's more likely to be an nginx core issue, rather than in ngx_lua because ngx_lua just uses the standard nginx C API to initiate the "filter finalize" operation.

One thing I don't quite understand in your original description is that `ngx.sleep` is disabled in the context of `header_filter_by_lua` and how is it possible for you to call `ngx.sleep(0.001)` right before `ngx.exit` in that context? Am I missing anything here?

**Comment by agentzh** [comment]
@danielfbento Okay, I've found that it is indeed a bug in the nginx core. In particular, in the `ngx_http_upstream_finalize_request` function. I'll prepare a patch for the nginx core and send it to you to try :) My quick dirty patch already fixes the timestamp issue on my side.

**Comment by agentzh** [comment]
@danielfbento Please try out the following patch for your nginx core:

https://raw.githubusercontent.com/openresty/ngx_openresty/master/patches/nginx-1.7.10-upstream_filter_finalize.patch

It should fix your problem.

**Comment by danielfbento** [comment]
@agentzh Thanks for the quick answer!

I patched my nginx (1.6.2) and until now, all the tests I made in the same conditions are running without any trouble.

I saw you sent the patch to the nginx-devel to! Thanks!  :)

**Comment by agentzh** [comment]
@danielfbento I recently fixed a bug in ngx_lua too, which may not be your current problem, but related. Better use the latest ngx_lua git master :)

**Comment by agentzh** [comment]
@danielfbento Oh, thank you for your feedback. Glad it works for you :)
