### ISSUE TITLE
Custom logging

### ISSUE THREAD

**Issue by jawadst** [openresty/lua-nginx-module#484]
Hi there,

I have a need to write custom log files that would be completely separate from Nginx's error/access logs and would have a completely free format. I couldn't find a way to do that by simply configuring Nginx and using ngx.log.
I could implement a simple Lua solution that simply writes to a file but I'd like to be able to take advantage of Nginx log compression and rotation (with kill -USR1). Is there any way to do that with the current implementation? If not, do you think that it's something that could be implemented in the module (or as a separate module) and made available through a "ngx.custom_log(file, content)" Lua function while still leveraging Nginx's native logging feature?

Btw, I use the Lua/Nginx module quite extensively on a daily basis and it works very well so thanks for the hard work!

Jawad

**Comment by agentzh** [comment]
@jawadst Glad you like ngx_lua. Regarding your question, you may want to look at the lua-resty-logger-socket library:

https://github.com/cloudflare/lua-resty-logger-socket

And you can create your own custom logger Lua module in a similar fashion. It does not have to be in the ngx_lua or nginx cores.

Socket-based logging is generally recommended for performance reasons because file I/O may almost always block the nginx event loop (or some OS threads if enabling the new nginx thread pool support for file I/O, still adding extra overhead).

**Comment by agentzh** [comment]
@jawadst BTW, you're recommended to join the openresty-en mailing list for such general discussions. And you may get more insights from other users and developers too. Please see http://openresty.org/#Community for more details.

**Comment by jawadst** [comment]
Great, thanks for the info!
