### ISSUE TITLE
failed to run factory

### ISSUE THREAD

**Issue by onexpiece** [openresty/lua-nginx-module#494]
机器在运行的时候遇到如下问题：
lua: failed to run factory at key "nhlf_b8b905
819665117ba0f24e853e6cf6b2": not enough memory
目前排查问题没什么思路，想问一下可能是什么原因引起的？

**Comment by agentzh** [comment]
@onexpiece Please, no Chinese here. This place is considered English only. Please join the openresty (Chinese) mailing list if you really want to use Chinese. Please see http://openresty.org/#Community

Regarding the error message, it is usually due to either

1. memory leak in your Lua code or 3rd-party Lua libraries you're using, or
2. excessive use of GC-managed memory in your Lua code (like allocating huge Lua strings or Lua tables without control).

**Comment by agentzh** [comment]
Consider it resolved.
