### ISSUE TITLE
DNS resolution with custom resolver fails intermittently

### ISSUE THREAD

**Issue by thefosk** [openresty/lua-nginx-module#504]
I am experiencing a weird issue related to DNS resolution when starting a TCP request with Lua, which sometimes seems to work and some other times doesn't. Specifically it seems like nginx is unable to always resolve `localhost` to `127.0.0.1` with a third part DNS resolver, but only intermittently.

### How to replicate

I have isolated the problem in the following code.

* `openresty/1.7.10.1` on OS X `10.10.3`
* I am using [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) v2.72 as a local DNS server, and I am running it with **no configuration** at `/etc/dnsmasq.conf` (delete that file if it exists):

    ```shell
    $ dnsmasq -port 8053
    ```
* I am using the following `nginx.conf` file:

    ```nginx
    worker_processes auto;
    error_log logs/error.log info;
    daemon off;

    events {
      worker_connections 1024;
    }

    http {
      resolver 127.0.0.1:8053;
      
      server {
        listen 9000;

        location / {
          access_by_lua '
            local sock = ngx.socket.tcp()
            local ok, err = sock:connect("localhost", 9001)
            if not ok then
              ngx.log(ngx.ERR, "failed to connect to localhost: ", err)
              ngx.say("error")
              ngx.exit(500)
            end

            sock:close()
            ngx.say("success")
            ngx.exit(200)
          ';
        }
      }

      server {
        listen 9001;

        location / {
          return 200 'Hello World';
        }
      }

    }
    ```

   This configuration starts two servers:
   * A simple test server on port `9001` that returns `Hello World`.
   * Another server on port `9000` that tries to connect to `localhost:9001`, and if the connection succeeds returns a `200` status code, otherwise returns a `500` status code.
    * `/etc/hosts` has the following entry: `127.0.0.1	localhost`

### Executing the test

Basically when making a request to `http://127.0.0.1:9000/`, the Lua code tries to resolve `localhost` and connect to the hello world server listening at `9001`. dnsmasq properly resolves `localhost` to `127.0.0.1`, so the connection should never fail.

Instead something weird happens: when nginx properly invokes the dnsmasq resolver at `127.0.0.1:8053` then `localhost` is being translated to `127.0.0.1`, but some other times instead it seems like the nginx resolver is unable to do so, and the operation fails:

```shell
$ while [ true ]; do curl 127.0.0.1:9000; done
success
success
error
success
success
success
success
success
error
success
error
success
success
success
error
^C
```

while the nginx error.log logs the following message:

```
2015/05/01 17:07:05 [error] 72109#0: *137 [lua] access_by_lua(nginx.conf:28):5: failed to connect to localhost: connection refused, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "127.0.0.1:9000"
```

In particular the server value seems to be empty: `server: `

### Thoughts

* The first though is that dnsmasq is not working properly, so I tried to manually query `localhost` against it:

    ```shell
    $ # The following operation never fails
    $ while [ true ]; do nslookup -port=8053 localhost 127.0.0.1; done
    ```

    And it seems to be always working.

* Excluding dnsmasq, the problem must be somewhere else. Could it be in the Lua code? Or in the way nginx internally uses the resolver?

**Comment by thefosk** [comment]
Looking at the dnsmasq logs, it seems like nginx successfully calls dnsmasq and dnsmasq successfully resolves the DNS address. The problem should be elsewhere, nginx is unable to use the proper IP address although being translated properly by the DNS server.

**Comment by agentzh** [comment]
@thefosk According to the error message you provided, "connection refused", it does not look like a DNS related issue at all, but rather, an issue while using the IP address to connect to 127.0.0.1:9001.

Your code example frequently opens and closes connections which may quickly exhaust your ephemeral ports in the system (UDP does not suffer from this issue though). Maybe enable connection pooling here via the `setkeepalive` method call of the cosocket objects?

Also, always retrying connecting while intermittent connect() errors happens is considered a best practice because intermittent errors could always happen due to packet loss or something. But if the error rate is usually high, it requires investigations.

**Comment by agentzh** [comment]
@thefosk Okay, I managed to reproduce the "connection refused" errors on my side (Mac OS X 10.9.5 + OpenResty 1.7.10.1 + dnsmasq 2.72) with your nginx configuration.

The reason for this error (at least on my side) is that my `/etc/hosts` file (loaded by dnsmasq by default) has the following IPv6 entries for "localhost":

```
::1             localhost
fe80::1%lo0	localhost
```

So if my OpenResty is built with the `--with-ipv6` option, then the nginx builtin resolver will query *both* IPv4 and IPv6 DNS records. And each request will pick up one DNS record by chance. When getting an IPv6 address, your `connect()` call receives a "connection refused" error. Why? Because by default nginx only listens on IPv4 addresses:

```
$ lsof -i:9001
COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
nginx   80461 agentzh    6u  IPv4 0x91e5ebb7b7ff2e69      0t0  TCP *:etlservicemgr (LISTEN)
nginx   80462 agentzh    6u  IPv4 0x91e5ebb7b7ff2e69      0t0  TCP *:etlservicemgr (LISTEN)
```

The "fix" is easy, I can just add the `ipv6=off` option to my `resolver` directive:

```nginx
resolver 127.0.0.1:8053 ipv6=off;
```

And then the errors go away completely.

Alternatively, I can make your stub server {} listen on those IPv6 addresses bound to "localhost" in my `/etc/hosts`.

You can check it out on your side. Good luck!

**Comment by agentzh** [comment]
@thefosk It's worth mentioning that I enabled the nginx debugging logs while investigating the issue. See the following official document on how to enable that:

http://nginx.org/en/docs/debugging_log.html

In particular, for your example, I noticed the following lines in nginx's error.log file:

```
$ grep "resolved to" logs/error.log
2015/05/07 17:51:24 [debug] 94930#0: *1 name was resolved to 127.0.0.1
2015/05/07 17:51:24 [debug] 94930#0: *1 name was resolved to ::1
2015/05/07 17:51:24 [debug] 94930#0: *4 name was resolved to ::1
```

Quite obvious, isn't it? ;)

**Comment by agentzh** [comment]
Oh, BTW, sorry for the delay on my side. I've been on my long vacation in China these weeks and I don't have sane Internet access for most of my time. Alas.

**Comment by thefosk** [comment]
@agentzh thanks for helping me debugging this issue and for the reference to the nginx debugging logs.

**Comment by kiddkai** [comment]
@agentzh 谢谢!!!! :dancer:

**Comment by czeludzki** [comment]
The same thing happened to me.
Because I let the "resolver" directive in http {}..
When I write the "resolver" in the location{}, it works fine.
Hope this can help others
