### ISSUE TITLE
nginx-lua-module中是如何使用多线程编程的的。

### ISSUE THREAD

**Issue by imiskolee** [openresty/lua-nginx-module#510]
grep源码看到了每个cotnentby最终都会变成一个线程执行。

我自己尝试使用Pthread进行多线程来处理request，进行ab测试的时候，会在某些时候段错误。

**Comment by imiskolee** [comment]
经过测试 nginx-lua也是一个worker一个request的处理方式？

**Comment by agentzh** [comment]
@imiskolee Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list. Please see http://openresty.org/#Community for more details. In addition, such general questions should go to mailing lists instead, no matter what language you're using.

Regarding your question, `content_by_lua` always creates a "light thread" for each request, which is NOT an operating system thread at all. Also, each nginx worker can handle a large amount of concurrent connections and requests at the same time, even with a single operating system thread. This is possible because of the power of multiplexing I/O and event-driven programming. If you are not familiar with these things, better learn the basics to save your time and my time :) Hope it helps.
