### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by splitice** [openresty/lua-nginx-module#527]
Hi,

I have been trying to get the full test suite passing for the purposes of doing CI testing with Travis-CI in my TravisCI branch (https://github.com/splitice/lua-nginx-module/tree/travisci). I have been experiencing some issues getting the tests to pass, 500 internal server errors and similar. Not really sure what I am missing.

The output of a build: https://travis-ci.org/splitice/lua-nginx-module

Any help?

**Comment by agentzh** [comment]
@splitice Upon a quick glance, I see the following issues in your nginx build:

1. you should link your nginx against PCRE 8.33 (later versions will pass the tests due to its behavior changes). Also you need to enable both JIT and UTF-8 in your PCRE build by specifying the `--enable-jit` and `--enable-utf8` options of `./configure`.
2. you seem to specify a custom --http-client-body-temp-path=PATH option while building your nginx. You need to at least put the string "client_body_temp" into your new PATH (as the default value does) because some of the tests assume that.
3. some of the tests require the patches applied by the OpenResty bundle: https://github.com/openresty/ngx_openresty/tree/master/patches

Taking care of these should fix most (if not all) of the test failures and then I can have another look if you have remaining failures.

Good luck!

**Comment by splitice** [comment]
Is it wise to require 8.33? Its no longer even available via the PCRE download server (too old) at ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/

**Comment by agentzh** [comment]
@splitice You're welcome to update the related tests for the latest PCRE version and submit a pull request :) I just won't have the time to update the tests any time soon.

**Comment by splitice** [comment]
I am not comfortable doing that, given that I have yet to get the tests running lack of availability for one of the dependencies being the first problem.

Version specific tests should really be avoided as it prevents the testing against newer versions for possible incompatibilities or regressions.

**Comment by agentzh** [comment]
@splitice Well, you just need to take care of those t/*-re-*.t test files, which do not require any external dependencies AFAIK. The tests are not really specific to PCRE 8.33; rather, it's just that later PCRE versions change the match limit behaviour. It's really a PCRE issue rather than ours. Hopefully PCRE does not change the match limit thing again in future releases, which is our best bet. Removing tests exercising this feature looks wrong to me. If you have a really portable way to do this right in existing tests, please let me know.

**Comment by agentzh** [comment]
@splitice BTW, PCRE 8.33 can be downloaded from here: http://linux.stanford.edu/pub/exim/pcre/pcre-8.33.tar.bz2

**Comment by agentzh** [comment]
@splitice I'd like to share the opsboy configuration file for setting up the *complete* environment on my Amazon EC2 test cluster:

https://github.com/openresty/opsboy/blob/master/samples/ortest-ec2.ob.tt

**Comment by splitice** [comment]
Ill add that standford mirror to the bash downloader. This weekend Ill be adding auto-patching from the patch repository you linked.

I hope that will get it passing finally (fingers crossed). 

I stand by what I said though, and it would be good to have later PCRE versions supported - I don't think I am the right person to do it though neither C or even less so Perl are my languages. Or atleast conditions skipping those tests when an untestable version is used.

**Comment by agentzh** [comment]
@splitice Nah, you don't need either C or Perl to do this. The test cases are (highly) declarative via a DSL and not in Perl at all. You only need to adjust the numbers in the corresponding nginx.conf snippets. Neither C nor Perl hacking will be needed :)

**Comment by splitice** [comment]
Is there some order for the patches at https://github.com/openresty/ngx_openresty/tree/master/patches?

I attempted applying them and got hunk failures (nginx 1.9.2). I don't see any file describing the intended order of application, unless I am missing something?

**Comment by agentzh** [comment]
@splitice Just use the `util/build2.sh` script to do the work for you. This script invokes the [ngx-build](https://github.com/openresty/nginx-devel-utils/blob/master/ngx-build) script under the hood.

**Comment by splitice** [comment]
Dont take this the wrong way but "this file is mostly meant to be used by the author himself", truer words have not been spoken. We tried farming out the project to our normal nginx / nginx-lua developer (contractor) and he couldn't get the tests running himself either (and he is much better at this kind of stuff than I). 

ngx-build was the hint I needed, I was looking for some form of patch list (or prefixed numbered ordering). Not entirely sure what to do with this, I dont really want to duplicate it, but at the same time ngx-build looks to have hardcoded paths and things in it (i.e https://github.com/openresty/nginx-devel-utils/blob/master/ngx-build#L144)

Our eventual aim is to take what we build here and use it to run the unit tests against own build (of course just the relevant ones to the modules enabled) and test for inter-op issues with our own patches. Of course you get a travis-ci compabile build file and a one .sh command to build a full testable environment from this stage :)

This should lower the barrier of entry for running the tests. I suspect very few people are able to run the full tests for issues, which is very important when running your own patch sets / modifications.

**Comment by agentzh** [comment]
@splitice The hardcoded path you mentioned is just relative to the current working directory, so not really a big deal :) A presumed directory layout simplifies things a lot (though not very flexible).

For in-house testing, you're recommended to share the same scripts and tools as I to minimise headache.

The wording "this file is mostly meant to be used by the author himself" is not so accurate and should be "this file is used by developers only" instead :) Already fixed in master and thanks for the catch:

https://github.com/openresty/lua-nginx-module/commit/51a311c04f0562864e068c3bb0e76a8b0a70b892

I'm always open to suggestions and patches which make the scripts and toolchain better for everyone :)

**Comment by splitice** [comment]
I agree that re-use of existing scripts is good, and lowers maitenance but ngx-build which takes on a lot of responsibilities with a hard coded method of operation.

It handles:
- Tarball Extraction
 - Patching
 - Compilation
 - Setup of execution environment.

Not very POSIX "Do one thing and do it well"

The main problem for integration with us is that it does all of this in one script, for example given that it goes right from tarball extraction to compilation there is no opportunity to inject our patches.

How would you feel about the creation of a command ngx-build-patch or something similar? Just split out that responsibility.

Something like, usage:
```
ngx-build-patch [path]
```

ngx-build can call it, so no functional changes.

**Comment by agentzh** [comment]
@splitice I'm fine with splitting `ngx-build`. Patches welcome :)

**Comment by agentzh** [comment]
Consider it resolved.
