### ISSUE TITLE
nginx proxy_cache_methods doesn't work

### ISSUE THREAD

**Issue by nguyennhatkhang92** [openresty/lua-nginx-module#561]
Hi,
I'm try use nginx proxy_cache for caching large file. The following is my idea:

 Browser --> Nginx --> Storage

-  Nginx is a function of caching and proxy server.
-  Storage is contain files server.
- I'm have used ngx.var.upstream_cache_status to determine the status of the HIT file caching but it does'n work, nil value. Then I found this: openresty/lua-nginx-module#125 . I would caching file with only GET method and use HEAD method is checked file caching done(HIT) but proxy_cache_methods doesn't work, proxy_method also. I'm try request from Browser with HEAD, GET method then nginx proxy pass to Storage server with GET methods, I do not understand what the reason.

**Comment by agentzh** [comment]
@nguyennhatkhang92 Because you didn't provide any code nor configuration, I can only guess here. Maybe you read the $upstream_cache_status variable too early or in a wrong context? For example, one should never read this variable in any phase before the header filter phase. In addition, one will not read any valid value in a parent request while the upstream thing is actually in the subrequest.

BTW, I don't understand your HEAD/GET method description.

**Comment by agentzh** [comment]
@nguyennhatkhang92 For such general discussions, please use the openresty-en mailing list instead:

https://openresty.org/#Community

This place is only for issues that are confirmed to be real issues in the module.

**Comment by nguyennhatkhang92** [comment]
Sorry, I would use https://openresty.org/#Community. Thanks @agentzh .

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by nguyennhatkhang92** [comment]
Ok, thank Yichun Zhang.
