### ISSUE TITLE
have same fastcgi_finish_request function?

### ISSUE THREAD

**Issue by qiye** [openresty/lua-nginx-module#573]
hi  agentzh
   
   I did't find same  PHP-FPM fastcgi_finish_request  function in lua-nginx-module.

**Comment by idevz** [comment]
hi @qiye may be you should try some like this to flush your response
```
ngx.header['Content_type'] = 'text/html; charset=UTF-8'
ngx.print(body)
ngx.say(body)
ngx.eof()
```
the output after ngx.eof will be droped for flush. 
One suggest for PHPer to Use Openresty， When you build up with Openresty, with Luajit and so Lua, It's a new place, Forgot your thought about PHP, PHP-FPM... because Openresty didn't need to transmit a requset to others, It's just deal with itself.
you May need one of my framework for PHPer based on Openresty [vanilla](https://github.com/idevz/vanilla)
very glad to discuss together with you.

**Comment by qiye** [comment]
@idevz thanks for your help. 
vanilla framework have lz-string for lua porting ?
http://pieroxy.net/blog/pages/lz-string/index.html

**Comment by idevz** [comment]
hi @qiye , vanilla didn't integrated lz-string right now, But ,If you need, you can very easy add it as a Third-party library. such as https://github.com/alexsilva/lz-string-lua.

**Comment by agentzh** [comment]
@qiye Yeah, you can use `ngx.eof` or `ngx.flush` to flush any pending data.
