### ISSUE TITLE
can I pass share variable to lua file?

### ISSUE THREAD

**Issue by adpoint** [openresty/lua-nginx-module#627]
lua_shared_dict rule 100m;
lua_shared_dict ruleb 100m;
   server {
        listen       80;
        server_name  localhost;
        access_by_lua_file test_rule.lua;

for example,use rule only in test_rule.lua, use ruleb in other lua file?

**Comment by membphis** [comment]
the lua file can control any shared_dict, there is no limited.

**Comment by adpoint** [comment]
sorry,I know that I can control any shard_dict in lua file,but I want to pass the shared_dict to the lua file,because I have only one lua file, controls one shared_dict, but I want different shared_dict,the lua file does not know to use which shared_dict.

**Comment by thibaultCha** [comment]
[See the documentation and examples](https://github.com/openresty/lua-nginx-module#ngxshareddict).

In your case:
```lua
-- in test_rule.lua
local dict1 = ngx.shared.rule -- the first dict
local dict2 = ngx.shared.ruleb -- the second dict

dict1:set("foo", "bar")
dict2:set("foo", "bar")
-- etc...
```

**Comment by adpoint** [comment]
in my case;

lua_shared_dict rule 100m;
lua_shared_dict ruleb 100m;
lua_shared_dict rulec 100m;
server {
listen 80;
server_name localhost;
access_by_lua_file test_rule.lua;  ###use rule
}
server {
listen 8080;
server_name localhost;
access_by_lua_file test_rule.lua; ###use ruleb
}
server {
listen 8081;
server_name localhost;
access_by_lua_file test_rule.lua; ###use rulec
}
.......
but in test.rule only use the same parameter,maybe access_by_lua_file test_lua.lua(ruleb),access_by_lua_file test_lua.lua(rulec) and so on.

**Comment by agentzh** [comment]
@adpoint I think you can make your Lua code a proper Lua module which exposes an entry point function, say, `go()`. Then in your `nginx.conf`, you can write

```nginx
    server {
        listen 8080;
        access_by_lua_block { require("test_rule").go("ruleb") }
    }

    server {
        listen 8081;
        access_by_lua_block { require("test_rule").go("rulec") }
    }
```

And your `test_rule.lua` file can be of this layout:

```lua
local _M = {}

function _M.go(shdict_name)
    -- your original Lua code goes here...
end

return _M
```

You need to configure the `lua_package_path` directive to make `require()` find your `test_rule` module though, for example,

```nginx
    lua_package_path "$prefix/?.lua;;";
```

**Comment by adpoint** [comment]
thanks!

**Comment by alubbe** [comment]
by the way, I've seen at https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Lua/openresty/nginx.conf#L12 that the require statement is run in the init_by_lua directive and saved to a global. Is this best-practice, does it have any performance implications or is it merely about personal preference?

**Comment by doujiang24** [comment]
Hello,

I don't think it's a good idea to use global variables

2015-12-22 17:14 GMT+08:00 Andreas Lubbe <notifications@github.com>:

**Comment by alubbe** [comment]
Could you elaborate why? A global variable lookup on the highest level in a
_by_lua block should be cheaper than having require look into its cache,
isn't it?

**Comment by bungle** [comment]
In general we do have some global variables in Nginx, such as `ngx`, and you still may want to localize them as you might want to have index lookup instead of hash lookup. But for other modules, you are actually polluting the global namespace. There is no agreement and it doesn't come out of the box that people agree e.g.:

```lua
encode = require "cjson".encode
mysql = require "resty.mysql"
```

This is what people mean about polluting global namespace. Those that work with OpenResty Lua Code and / or Lua Modules don't expect there to be global `encode` (that is JSON encoding) or global `mysql`. You may try it on your personal projects, but this is getting quickly messy when there are more contributors (say a team).

So in general it is better to write modularized Lua code (even the simplest things can be modularized), and then at the top of the module you cache the objects to local variables that can be retrieved then with simple index lookup (Lua does this automatically), e.g.:

```lua
local mysql = require "resty.mysql"
local encode = require "cjson".encode
```

Sometimes you need stateful objects, e.g. `mysql:new()`in many places. You should not share that object between Nginx workers, or even between single Nginx worker's light-threads. It is better to pass that to other modules and functions as function arguments rather than leveraging on global variables. This is about hygiene in code (avoiding race conditions etc.).

You may have seen code like:

```lua
require "resty.core"
```

in `init_by_lua`, but that is a core library. What this does is that it replaces Lua C API bindings with LuaJIT bindings (e.g. it overwrites global ngx functions for example). Even this doesn't come without the problems of its own. One problem is that all of these bindings are not 1:1, one example about it is that Lua C API is quite strict on function argument counts, but `resty.core` is more forgiving (e.g. sometimes code runs just fine with when using `resty.core` but when removing that, the code may start throwing errors.

**Comment by agentzh** [comment]
@alubbe This is actually documented: https://github.com/openresty/lua-nginx-module#lua-variable-scope But apparently @bungle does a better job in explaining this (above) :)

**Comment by alubbe** [comment]
Thanks for the in-depth answers!
I was actually only trying to understand the one special case below and whether there are any performance gotchas or anything else to watch out for other than good coding practices:
```
    init_by_lua_block { testRule = require("test_rule") }
    server {
        listen 8080;
        access_by_lua_block { testRule.go("ruleb") }
    }

    server {
        listen 8081;
        access_by_lua_block { testRule.go("rulec") }
    }
```
vs
```
    server {
        listen 8080;
        access_by_lua_block { require("test_rule").go("ruleb") }
    }

    server {
        listen 8081;
        access_by_lua_block { require("test_rule").go("rulec") }
    }
```
I understood the benchmark implementation as using every available trick to squeeze out performance, hence my question.
But I feel that I may have derailed this issue - feel free to close, I would re-open a separate issue.

**Comment by agentzh** [comment]
@alubbe Well, (ab)using Lua globals there should be a little bit faster than require() though I'd be surprised if you would see any measurable difference when benchmarking on the HTTP level :)

**Comment by alubbe** [comment]
Thanks for clearing that up. Are there benefits or gotchas from having run the require in the init block and thus, pre-forking?

**Comment by agentzh** [comment]
@alubbe Actually pre-loading Lua modules in the `init_by_lua` phase is usually recommended (only the module loading code creates new file descriptors) since you have a chance to save physical memory via modern operating systems' COW feature. But use of Lua globals is discouraged and the reasons have already been well explained above I believe :)

**Comment by alubbe** [comment]
So that's a yes to my last question, right?
Thanks again and sorry for hijacking this issue.

**Comment by agentzh** [comment]
@alubbe Yes, that's a "yes", definitely :)

**Comment by adpoint** [comment]
init_by_lua_block { testRule = require("test_rule") }
    server {
        listen 8080;
        access_by_lua_block { testRule.go("ruleb") }
    }

    server {
        listen 8081;
        access_by_lua_block { testRule.go("rulec") }
    }
I use this method,but have some error, "attempt to call method 'get' (a nil value)" in test_rule.lua,i think ruleb or rulec did not pass in or some error?

**Comment by agentzh** [comment]
@adpoint Seems like you're (ab)using Lua global variables. That error message is a common signal of such misuses.

**Comment by adpoint** [comment]
test_rule = {}
   function test_rule.go(rule)
       local default_ttl = 3;
        local func = require ("func");
        --main process
        local time_stamp  = ngx.time();
                local global_switch, flag = rule:get("switch");
        if flag == 0 or global_switch == nil or global_switch == "off" then
            return
        end

the rule is pass by testRule.go("ruleb"),the error is the statement "                local global_switch, flag = rule:get("switch");"

**Comment by thibaultCha** [comment]
`rule` is a string. What you want is to retrieve the shared dict with that name, as in the example I showed you:

```lua
local dict = ngx.shared[rule]
dict:get()
```

**Comment by agentzh** [comment]
@adpoint BTW, please check out OpenResty's `lua-resty-*` libraries to see how to correctly code up a Lua module. In your code, `test_rule` is a Lua global and you should return the module table at the end of your module Lua file.

**Comment by agentzh** [comment]
@adpoint It's a good idea to always run the `lua-releng` tool to check any Lua global misuses as documented in the aforementioned document section: https://github.com/openresty/lua-nginx-module#lua-variable-scope

Again: using Lua global variables is a really really bad idea.

**Comment by adpoint** [comment]
ok, thanks very much, i will learn how to code up a Lua module now!

**Comment by agentzh** [comment]
Consider it resolved.
