### ISSUE TITLE
http code 204 and API calls

### ISSUE THREAD

**Issue by OlegKapustenko** [openresty/lua-nginx-module#666]
Hey guys,

Does anybody know how to use API calls in the case of OPTIONS http request?
That request is being used for CORS and returns some access controlling headers with the code 204 (No Content).
Since the answer doesn't contain any body I was not able to use access_by_lua or something like this.
My code makes some network requests to the redis db and I have not invented how to avoid this.
Here is an example of my access_by_lua code
    set $lua_ref '';
    set $thekey 'mykey';
    access_by_lua '
        local redis = require "resty.redis"
        local red = redis:new()
        local ok, err = red:connect("1.2.3.4", 6379)
        if not ok then
            ngx.exit(403)
            ngx.var.lua_ref = 0
            return
        end
        ok, err = red:select("35")
        if not ok then
            ngx.exit(403)
            ngx.var.lua_ref = 0
            return
        end
        ok, err = red:get(ngx.var.thekey)
        if not ok then
            ngx.exit(403)
            ngx.var.lua_ref = 0
            return
        end
        ngx.var.cors = ok
    ';

Any suggestions how to use redis API in OPTIONS/204 requests?

**Comment by agentzh** [comment]
@OlegKapustenko `access_by_lua*` usually runs before response is generation. So it does not make sense at all to check response headers in that context since responses do not even exist in that phase. Regarding your use cases, it seems that using `ngx.location.capture` to initiate a subrequest to your origin is more appropriate (or using any of those `lua-resty-http*` libraries out there directly).

BTW, such general questions should go to the openresty-en mailing list instead. Please see https://openresty.org/#Community Thanks for your cooperation.

**Comment by OlegKapustenko** [comment]
Will check it.
Thanks.

**Comment by agentzh** [comment]
Consider it resolved.
