### ISSUE TITLE
Feature request: API for proxy_set_header in balancer_by_lua_block

### ISSUE THREAD

**Issue by AWooldrige** [openresty/lua-nginx-module#697]
It would be very convenient to be able to set headers in the HTTP requests to the upstream from the `balancer_by_lua_block` mechanism. In particular, the `Host` header which can depend on the peer.

**Comment by agentzh** [comment]
@AWooldrige It's already too late the change the request header in the context of `balancer_by_lua*` because the upstream request is already generated at that point. For you use case, you should do the request header preparation in an earlier phase, like `access_by_lua*` via the `ngx.req.set_header` Lua API, for example.

**Comment by AWooldrige** [comment]
Thanks for looking into this @agentzh. Fair enough, I see this would be difficult to implement if the request is already prepared. We'll workaround using the suggestions you have provided, thanks!
