### ISSUE TITLE
ngx.timer.at will not keep correct if system time is changed

### ISSUE THREAD

**Issue by aaashun** [openresty/lua-nginx-module#707]
I am not sure this is a issue or a designed feature, this problem is widely exists in many software or programming languages.

the root reason is that the timer is based on 'real time', not 'monotonic time'

1. add code block in nginx.conf --> http --> server:

         location /update_time {
             content_by_lua 'ngx.update_time()';
         }   
  
         location /timer_at {
              content_by_lua '
                  ngx.log(ngx.ERR, "000")
                  ngx.timer.at(60, function() -- 60s delay is expected
                      ngx.log(ngx.ERR, "111")
                  end)
              ';
          }

2. reload nginx and watch logs
> sudo /usr/local/openresty/nginx/sbin/nginx -s reload
> tail -f /usr/local/openresty/nginx/logs/error.log

3. request
> su
> curl localhost/timer_at; date --set "+60 seconds"; curl localhost/update_time

you will notice that in the log window, the two lines '000' and '111' are printed in a short time

**Comment by agentzh** [comment]
@aaashun Yes, the nginx timer mechanism is using absolute timestamps to organize the red-black tree of all the created timers. This simplifies and speeds up the implementation a lot since we do not have to maintain "ticks" and update all the timers on every tick on the userland ourselves. For similar reasons, the shm entry expiration times are stored as absolute timestamps as well. It's common practice.

Regarding your issue, I think you should really do the timestamp update itself monotonically or gradually, like what the ntpd service does by default, otherwise you may have issues with processes other than nginx as well I'm afraid.
