### ISSUE TITLE
the print func in resty will not auto translate table to string

### ISSUE THREAD

**Issue by iorichina** [openresty/lua-nginx-module#720]
codes like below, does it a bug or special usage?
```
# /usr/local/luajit-2.0.3/bin/luajit -e 'local tb,tb2={a=1,b=2},{c=3};print("{",tb,"-",tostring(tb2),"}")'
{	table: 0x404d6cb0	-	table: 0x404d6d10	}

```
```
# /usr/local/openresty-1.9.7.2/bin/resty -e 'local tb,tb2={a=1,b=2},{c=3};print("{",tb,"-",tostring(tb2),"}")'
{-table: 0x404533a8}

```
```
# lua -v
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
# lua -e 'local tb,tb2={a=1,b=2},{c=3};print("{",tb,"-",tostring(tb2),"}")'
{	table: 0x21b9560	-	table: 0x21b9330	}

```

**Comment by agentzh** [comment]
@iorichina ngx_lua uses a different implementation of `print`, for obvious reasons, because STDOUT makes no sense in the context of a web server daemon. Also, `print` does not add a (tab) separator for arguments. This is also the behavior we want (so that it's easier to control formatting without concatenating Lua strings on the Lua land).

**Comment by iorichina** [comment]
i see, thanks.
