### ISSUE TITLE
ngx.timer.at why not work? connect mysql ?

### ISSUE THREAD

**Issue by winfan** [openresty/lua-nginx-module#755]
ngx.ctx.dbconf = {
    host = "127.0.0.1",
    port = 3306,
    database = "test",
    user = "root",
    password = "123456"
}
package.path = package.path .. ";/Users/winfan/Documents/Project/openresty-test/app/lib/?.lua;;";
package.path = package.path .. ";/Users/winfan/Documents/Project/openresty-test/app/lib/lua-resty-http/lib/?.lua;;";
local cjson = require "cjson"
local utils = require ("utils")
local mysql = require "resty.mysql"
local db = mysql:new()
local ok, err, errno, sqlstate = db:connect(ngx.ctx.dbconf)
 

local sid = ngx.shared.sid 

 

 local handler

 handler = function(db,cjson,dbconf)
    local cjson = require "cjson"
    local sid = ngx.shared.sid  
     --getSid();
     local num = 300000
     ngx.log(ngx.ERR, "error:",cjson.encode(sid:get("a")))
      sql2 = "SELECT max FROM test.sid where id='1';"
--     res2,err2,errno2,sqlstate2 = db:query(sql2)
--     cm =  res2[1]['max']

      sql1 = "UPDATE `test`.`sid` SET `max`= `max`+"..num.." WHERE `id`='1';"
--     res, err, errno, sqlstate = db:query(sql1)
     --sql2 = "SELECT max FROM test.sid where id='1';"
     --db:query(sql2)
  
     local ok, err = ngx.timer.at(2, handler, db,cjson,dbconf)
    ngx.log(ngx.DEBUG, "ok:", ok, " err:", err)
end

 local ok, err = ngx.timer.at(0, handler, db,cjson,dbconf)  --here why db argment passed into useless it?
@agentzh 
ngx.log(ngx.DEBUG, "ok:", ok, " err:", err)
if not ok then
    ngx.log(ngx.ERR, "err:", err)
end 

local ok, err = db:set_keepalive(10000, 500)
if not ok then
    ngx.log(ngx.ERR, "failed to set keepalive: ", err)
    ngx.exit(500)
end

**Comment by agentzh** [comment]
@winfan Three obvious mistakes:

1. appending to the VM-level `package.path` field in request handlers result in ever growing `package.path`'s value and memory leaks. Do that only in run-once contexts like `init_by_lua*` or just use the `lua_package_path` nginx directive in your `nginx.conf`.
2. the timer handler always accepts the `premature` argument as its first parameter. Please read the documentation of `ngx.timer.at` more carefully.
3. You cannot pass a cosocket object (via a `resty.mysql` object for example) to the timer handler since cosockets cannot be used outside the (request) context where they are created. See https://github.com/openresty/lua-resty-mysql#limitations

**Comment by winfan** [comment]
thks @agentzh
