### ISSUE TITLE
lua_package_path too long

### ISSUE THREAD

**Issue by FrancisHe** [openresty/lua-nginx-module#763]
Some times, we need to load lots of Lua libraries or Lua file, which will result in very long lua_package_path. It's unfriendly to read or edit. For example:

> lua_package_path    '/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib64/lua/5.1/?.lua;/usr/lib64/lua/5.1/?/init.lua;;';

Is there any method to avoid that like this:

> set $default_path1 '/usr/share/lua/5.1/?.lua';
set $default_path2 '/usr/share/lua/5.1/?/init.lua';
lua_package_path    '${default_path1};${default_path1};;';

**Comment by agentzh** [comment]
@FrancisHe Maybe you can just assign to `package.path` in your `init_by_lua*` handler? This way you can use the full Lua magic to assemble your search path strings.

You cannot use custom nginx variables there since nginx variables are per-request constructs while `lua_package_path` is a global thing where requests do not even exist.

**Comment by FrancisHe** [comment]
OK, thanks @agentzh
