### ISSUE TITLE
Issues with broken client connections

### ISSUE THREAD

**Issue by jsopenrb** [openresty/lua-nginx-module#771]
Sometimes memory is not freed, nginx hangs or crashes with a segfault when client connection gets broken/closed in the middle of a request. I'm testing it on a rather slow ARM board, but the same issue has been caught on x86 VM.

Test script is quite simple, just many short writes. Testing in a browser by quickly pressing F5 several times so all requests but the last are closed prematurely.
`for i = 1, 1000 do ngx.say(i) end`

Nginx config is pretty much standard, `reset_timedout_connection` is enabled, but I think I had the same issue with `reset_timedout_connection` disabled.

Enabling debug slow things down so it might be harder to find this issue. Part of debug log where connection is broken.
> 2016/05/19 09:04:04 [info] 13128#0: *1 writev() failed (32: Broken pipe), client: 192.168.1.204, server: , request: "GET /test HTTP/1.1", host: "192.168.1.10"
2016/05/19 09:04:04 [debug] 13128#0: *1 http write filter FFFFFFFF
2016/05/19 09:04:04 [debug] 13128#0: *1 http copy filter: -1 "/test?"

Is there any way of stopping the Lua script if `connection->error` becomes 1 during write?

Thanks in advance! I can provide some more info, do some tests or provide remote access if that helps.

**Comment by jsopenrb** [comment]
Forgot to mention that I'm using latest lua-nginx-module from git and nginx 1.10.0, but had this issue with older nginx and lua module.

**Comment by alubbe** [comment]
I think part of the reason could be that you are looping over `ngx.say`, which you shouldn't. Instead build up the string in lua and, once done, pass it `ngx.say`.

**Comment by jsopenrb** [comment]
This is just a test case, real application has one or just several ngx.say calls, but the problem is still there.

**Comment by agentzh** [comment]
@jsopenrb Client aborts during writes are specifically tested in the official test suite. And we've never seen such crashes in CloudFlare's global network running OpenResty.

My hunch is that your crashes are due to something else. You should examine the core dump file via tools like gdb. See

https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#core-dump

BTW, we also have production users running OpenResty on slow ARM boards :)

The real issue here is that `ngx.say()` can return errors. You should check that in your own Lua code. Try the following instead:

```
for i = 1, 1000 do
    local ok, err = ngx.say(i)
    if not ok then
        break
    end
end
```

The hanging part you see should be that your accumulate too many busy loops flooding your nginx error logs. You need to use the flame graph tools to be sure: http://openresty.org/en/profiling.html

The crashing part might be that you exceed the LuaJIT VM memory limit due to too many accumulated busy Lua light threads. But we still need to check the core dump file via gdb (as mentioned before) to be sure.

I tried your example and steps locally and could not reproduce any crashes or memory leaks, BTW. But still, you really need to handle any errors returned by `ngx.say()` to be honest.

**Comment by agentzh** [comment]
@jsopenrb wrote
> Is there any way of stopping the Lua script if connection->error becomes 1 during write?

No, `ngx.say` returns the error instead of throwing out the error. The latter is too aggressive. It's much more efficient and convenient (for the Lua VM) to handle the error by checking return values instead of catching an exception.

**Comment by jsopenrb** [comment]
Thanks for your suggestions, I'll provide some more info later on. I agree that `ngx.say` result should be handled but we can't force users who might write their own code to do it :( Still, it's more of an edge case that won't be usually seen in production. Can you point me at where to look if the request memory is not freed during these tests?

Segfault/sigill errors are very rare and are quite hard to catch. Can there be some kind of a race condition between nginx core and Lua module? Like if Lua module is trying to access memory that has already been freed?

**Comment by agentzh** [comment]
@jsopenrb Can we stop guessing wildly? Without enough information, we are just wasting our time here and won't go anywhere.

I've already suggested tools that you can use to analyze process hanging and crashes. Please use them. Ensure that you can reproduce the issues without 3rd-party Lua modules or 3rd-party Nginx C modules that are not maintained by OpenResty. We're not responsible for code that we do not maintain.

Also, you should never allow your user to directly inject arbitrary Lua code into your server. This module is not designed to be a runtime sandbox at all. And the user can easily screw your server up in millions of ways. The simplest way is an infinite loop:

```lua
while true do end
```

For user-defined logic, you should devise a domain specific language and compiler that can enforce rules and limitations easily and always generate well-formed safe-to-run Lua code for this platform. This is a kind of "compile-time sandbox", which is much safer and much more efficient at runtime.

As I've said, significant efforts have been put on testing and ensuring that this module does not have issues even on extreme conditions like client aborts and concurrent accesses. And we have a lot of large-scale production users worldwide. If you think there is a bug in this module, please provide a standalone and minimal example with precise steps that we can (relatively) easily reproduce the issue on our side. See below for how to report a problem:

http://openresty.org/en/faq.html

**Comment by jsopenrb** [comment]
Whoa, no need to be so critical :) I understand your pain of having incomplete bug reports, but it happens that some bugs are rare and quite hard to catch. Anyway, there are no 3rd-party nginx modules, there are some Lua modules which are just C-bindings which never caused any issues outside of nginx in the past. I've enabled core dump support so hopefully I can provide a proper backtrace soon.

As for user-defined logic: since it's running on their own devices they can do whatever they like, including shooting their own feet.

**Comment by jsopenrb** [comment]
I've managed to reproduce the hanging issue with many short `ngx.say` calls. In this case the client connection is ok, but at some point nginx starts consuming all available CPU power.

It's pretty hard to trace as enabling even a small amount of logging adds a slight delay between output calls and the issue goes away. This happens when `ngx_http_write_filter` returns `NGX_AGAIN` in `src/http/ngx_http_write_filter_module.c` here:

```c
if (chain) {
    c->buffered |= NGX_HTTP_WRITE_BUFFERED;
    return NGX_AGAIN;
}
```

Calling `ngx_http_lua_ngx_flush` with `wait=true` in `ngx_http_lua_ngx_echo` in case `ngx_http_lua_send_chain_link` returns `NGX_AGAIN` seems to help.

Providing a proper test case is tricky because this issue depends on many factors as CPU power / network latency etc.

**Comment by agentzh** [comment]
@jsopenrb Calling ngx.say/ngx.print too often in a single request handler without `ngx.flush(true)` and etc is just wrong usage. And this is documented officially:

> Please note that both ngx.print and ngx.say will always invoke the whole Nginx output body filter
> chain, which is an expensive operation. So be careful when calling either of these two in a tight
> loop; buffer the data yourself in Lua and save the calls.

https://github.com/openresty/lua-nginx-module#ngxprint

Because these functions are expensive, calling them too often will surely exhaust your CPU resources and lead to what you describe as a "hang". I don't think we should be responsible for such wrong usage.

And @alubbe already pointed out here much earlier. Please read our comments carefully otherwise we feel our time is wasted while trying to help you.

**Comment by agentzh** [comment]
@jsopenrb Also, please read the documentation more carefully. The docs are there for a reason.

**Comment by jsopenrb** [comment]
Ok, feel free to close this issue, I still think that say/print should check for `NGX_AGAIN` though. Adding explicit flush in case of `NGX_AGAIN` works for me anyway. Thanks for your help!

**Comment by agentzh** [comment]
@jsopenrb No, `ngx.say`/`ngx.print` is asynchronous by default. And there's no reason to call flush automatically. The `ngx.flush` is provided when the caller wants such control.

**Comment by agentzh** [comment]
@jsopenrb By design, slow clients should never slow down the `ngx.say`/`ngx.print` calls. That's what I said about "asynchronous". This is also officially documented. If you want otherwise, you should call `ngx.flush(true)` on the Lua land instead. You were asking me to change the semantics of `ngx.say`/`ngx.print`, which won't happen even for the sake of backward-compatibility.
