### ISSUE TITLE
Expires directive always overrides user-defined Cache-Control response header

### ISSUE THREAD

**Issue by gnought** [openresty/lua-nginx-module#806]
It seems that Cache-Control response header cannot be overridden when a "expires" directive is set. Could you clarify the meaning of the documentation "Here is an example of overriding a response header (or adding one if absent) in our Lua header filter:" ? or is it a bug or limitation?

```
location = /ddd/ {
  expires 5m;
  default_type 'text/plain';
  header_filter_by_lua_block {
   ngx.header.Cache_Control=nil
   ngx.header.Cache_Control="Blah"
  }
  return 200;
}
```

**Comment by agentzh** [comment]
@gnought There is an order in running the nginx output header filters registered by different nginx modules. Basically, the `expires` directive is implemented in the output header filter registered by ngx_http_headers_filter_module, which runs after almost all the other header filters, including ngx_lua's header filter. So your Cache-Control header set in `header_filter_by_lua_block` just got overridden by nginx's own ngx_http_headers_filter_module's filter which runs afterwards.

A solution to this problem is to avoid using the `expires` directive in the first place, and just implement the logic all in your Lua header filter processor. Not a big deal.

**Comment by agentzh** [comment]
@gnought BTW, when in doubt, you can always use tools like `ngx-header-filters` to inspect the actual running order of nginx header filters on the fly:

https://github.com/openresty/nginx-systemtap-toolkit#ngx-header-filters
