### ISSUE TITLE
Capitalizing headers

### ISSUE THREAD

**Issue by danihodovic** [openresty/lua-nginx-module#820]
I'm trying to set headers in a Lua block. When calling `ngx.header['Foo']` OpenResty/Nginx will by default return the header name in lowercase. I'm aware that HTTP headers are case-insensitive, but I was wondering if it's possible to work around this and capitalize a header using Lua?

**Comment by agentzh** [comment]
@danihodovic `ngx.header['Foo']` returns the header value instead of the header name, so I have no idea why you are talking about the letter case in header names returned. I'm really confused.

Maybe the following API function is what you want:

https://github.com/openresty/lua-nginx-module/#ngxrespget_headers

BTW, it accepts a `raw` boolean argument to return header names in their original letter case.

**Comment by danihodovic** [comment]
I was talking about setting headers, not getting them as per https://github.com/openresty/lua-nginx-module#ngxheaderheader

**Comment by agentzh** [comment]
@danihodovic Please provide a minimal code example otherwise I really have no idea what you're talking about since there are millions of different ways for a green user to get things wrong :)

**Comment by danihodovic** [comment]
I'm an idiot. As I was patching together an example I realized using capitalized header names works.

```
ngx.header['X-My-Captialized-Header'] = 'bar'
```

```
$ curl -v localhost
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
...
< HTTP/1.1 429
...
< X-My-Captialized-Header: bar
...
```

**Comment by agentzh** [comment]
So what was the issue? Typos?

**Comment by danihodovic** [comment]
I can't remember exactly, but I think the HTTP client library I was using to test the OpenResty logic used case-insensitive keys for the headers.
