### ISSUE TITLE
ipv6+ngx_lua problem

### ISSUE THREAD

**Issue by cjhust** [openresty/lua-nginx-module#832]
compile with "--with-ipv6"
not listen ipv6, listen ipv4

but some ipv6 log appear in error.log 

2016/08/04 19:39:38 [error] 3475351#0: connect() to [2001:590:1c09:18a::201a]:80 failed (101: Network is unreachable), context: ngx.timer, client: 113.103.62.33, server: 0.0.0.0:443

**Comment by agentzh** [comment]
@cjhust I'm guessing it is because your network does not really support IPv6 but your DNS server returns IPv6 addresses. Try putting the following line in your nginx.conf:

```
resolver xx.xx.xx.xx ipv6=off;
```

See http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver for more details. Another option is to disable IPv6 support altogether in your nginx build but disabling IPv6 in your resolver setting should already be sufficient.

**Comment by cjhust** [comment]
Thanks

**Comment by agentzh** [comment]
@cjhust You've solved the problem? If yes, please close this issue. Thank you!
