### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by es** [openresty/lua-nginx-module#843]
Would it be valuable to submit a patch with a Vagrantfile to make it easy for newcomers to setup a development environment?

**Comment by agentzh** [comment]
@es Because I do not use Vagrant myself to do the development, it would be quickly out of sync if it were checked in. I suggest you roll out your own Vagrantfile by looking at the .travis.yml file for Travis CI testing. The environment set up instructions in that file will always be up to date since we all rely on Travis CI nowadays.

**Comment by es** [comment]
I'll update this issue pointing to a gist with the Vagrantfile for anyone that uses vagrant in the future.

**Comment by es** [comment]
[Here's the link to the Vagrantfile](https://gist.github.com/es/e44d93ee43b17afe825e1ab4178ddfd0) for anyone interested.
