### ISSUE TITLE
https cert problem

### ISSUE THREAD

**Issue by cjhust** [openresty/lua-nginx-module#895]
nginx.conf：
  ssl_certificate                    ssl/xx.pem;$                          //   (have cert chain)
  ssl_certificate_key              ssl/xx.key;$
  ssl_certificate_by_lua_file    ssl_cert.lua;
...

ssl_cert.lua：
ssl.clear_certs()
ssl.set_der_cert(cert_data)                                                // (have no cert chain)
...

#openssl s_client -connect 127.0.0.1:443 -servername 'yy.com'  -showcerts
expect return server_cert only
but return server_cert+cert_chain

when I read source, find **ssl_add_cert_chain()**

    /*
     * If we have a certificate specific chain use it, else use parent ctx.
     */
    if (cpk && cpk->chain)
        extra_certs = cpk->chain;
    else
        extra_certs = s->ctx->extra_certs;  //here leads to the parent ctx's cert_chain returned

**Comment by cjhust** [comment]
I think clear_certs() need to clear parent ctx

**Comment by cjhust** [comment]
ngx_http_lua_ffi_ssl_clear_certs() need to add
  SSL_certs_clear(ssl_conn);$
+ssl_conn->ctx->extra_certs = NULL;$

**Comment by agentzh** [comment]
@cjhust I'm not sure about this. AFAIK, we never had any problems with `clear_certs` in CloudFlare's global SSL gateway.

@lziest @ghedo What do you think of this?

**Comment by cjhust** [comment]
thanks for you reply.
the cert without the cert chain is setted by our users.
certainly this way setting just only server cert  is wrong, but I think server cert joins the defaut-server's chain is also wrong.

**Comment by agentzh** [comment]
Please provide a minimal and standalone example that can reproduce the issue easily on our side. Thank you.

**Comment by cjhust** [comment]
your email address? 
the email sending to agentzh@gmail.com is returned.

**Comment by agentzh** [comment]
@cjhust That *is* my email address.

**Comment by lziest** [comment]
@cjhust @agentzh This is a corner case of how OpenSSL handles certificate.

I believe here is what is happening.
`ssl_certificate ssl/chain.pem;` `chain.pem` contains more than 1 certificate.
nginx/openssl will store all the certificates other than the 1st one into `extra_certs`.
Simply replacing the 1st certificate (the leaf cert) by `set_der_cert(single_cert_x509)` won't touch `extra_certs`.
So visiting the server we will see the leaf certificate being replaced, with all the rest of certificate chain untouched.


@cjhust if you try `set_der_cert` with more than one certificates, would you see the extra certificates being replaced with desired chain?

I don't think we should clear `extra_certs` with `set_der_cert` because it is out of the scope of such operation. We can't change default config with operations on one connection. It's totally OpenSSL idiocy. Looking through the OpenSSL `ssl_add_cert_chain`, we can see it is exactly how the logic flow: if the certificate has a chain, use it; otherwise, use the default one.

**Comment by agentzh** [comment]
I agree this is too much a corner case to be interesting. In reality, we almost always use a chain as the input anyway.

**Comment by cjhust** [comment]
I agree this is too much a corner case to be interesting. thank you.
