### ISSUE TITLE
TCP cosockets mixing responses for different connections

### ISSUE THREAD

**Issue by kipras** [openresty/lua-nginx-module#921]
Hey,

we've run into a major problem with tcp cosockets in ngx_lua - the responses are mixing up for different sockets. This happens when all these conditions are true:
* connection has a small read timeout set (the smaller - the higher the chance of hitting this bug)
* connection has keepalive enabled : https://github.com/openresty/lua-nginx-module#tcpsocksetkeepalive
* both connections connect to the same IP and the same port

When there are many connections - this issue happens at some point during nginx lifetime. However it's not deterministic - you have to stress the server for this to happen. I attached configuration to reproduce this (see below).

So far we've disabled keepalives to workaround this and it looks to be working. However this increases latency by a bit, so we'd like to enable them again.

We've also been debugging ngx_lua for some time and arrived to this:
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_socket_tcp.c#L3162

The `ngx_http_lua_socket_tcp_finalize()` call in `ngx_http_lua_socket_handle_read_error()` is currently disabled. If it is enabled - this issue goes away.
The change was made as part of this commit: https://github.com/openresty/lua-nginx-module/commit/e8aa2495f37b17ce2def5aa9f22f74f9a4ff0754

	bugfix: for big input data, the cosocket reading methods could result…
	in crashes due to incorrect use of luaL_Buffer. now we eliminate luaL_Buffer altogether by managing the recv buffers ourselves. the recv buffers can also be recycled.

I'm not really understanding the issue mentioned in the commit or the change itself, could you explain why it is necessary? And what the removal of `ngx_http_lua_socket_tcp_finalize()` changes?
Could we work around this somehow?

Also, i'm not stating that the removal of `ngx_http_lua_socket_tcp_finalize()` is the exact reason causing this issue, i'm just stating our findings.

Also, i've searched through existing lua-nginx-module issues (because i could not believe that we're the only ones seeing this) and did not find many related issues, however this one seems to be of the same issue: https://github.com/openresty/lua-nginx-module/issues/316

Issue confirmed on: ngx_lua versions 0.9.19 (OpenResty 1.9.3.2), 0.10.6 (OpenResty 1.11.2.1), 0.10.7 (OpenResty 1.11.2.1)
OS: Ubuntu 14.04 LTS x64

Reproducing steps:
1. download config files: [reproduce_configs.zip](https://github.com/openresty/lua-nginx-module/files/609788/reproduce_configs.zip)
2. add this to your hosts (/etc/hosts) file:

	127.0.0.1 	app_1.test
	127.0.0.1 	app_2.test

3. install nodejs if you don't have it (the script for the origin runs nodejs)
4. run run_servers.sh - it will start the nodejs origin servers
5. download https://github.com/pintsized/lua-resty-http and make sure ngx_lua can load it. It is used by the sample websites and is what makes the cosocket connections to proxy the request (where the issue happens).
6. start OpenResty, make sure it loads those 2 config files. OpenResty should be installed in the default location /usr/local/openresty otherwise this test may not work - you may need to modify it.
7. open app_1.test and app_2.test in your browser. app_1.test should load, app_2.test may time out (this is fine).
8. start the provided run_stress.sh script
9. run check.sh - it will report the number of mixups found, by looking at the logs. You can also check logs manually - they are minimized to contain a json line with the response upstream peer and a response header with the origin webapp name.
10. kill stress test by running kill_stress.sh
11. kill origin servers (you can use kill_servers.sh)

If all is working correctly - the check.sh script should start reporting mixups sometime during the first minute after launching the stress test.

If you cannot reproduce - make sure nodejs for origin (or nginx itself) is not killed for running out of memory. In that case you may want to run it in a VM (via vagrant for example).

If you still cannot reproduce - write here, i'll help you.

Thanks and best of luck.

**Comment by agentzh** [comment]
@kipras It looks like you are abusing Lua global variables in your Lua code. Please read this doc section first:

https://github.com/openresty/lua-nginx-module#lua-variable-scope

Ensure you have used the `lua-releng` tool to clear out all misuses of Lua global variables.

**Comment by agentzh** [comment]
@kipras BTW, for test cases, it's recommended to make it self-contained and minimal, which means you'd better use openresty directly as the backend instead of introducing external components like nodejs in your test case.

**Comment by kipras** [comment]
@agentzh sorry for the convoluted test case. I just sent everything that we had while working on this issue, we spent quite some time.. :)

Which part of that Lua code abuses global vars? There's only two variables and they are both local. Is there something i'm missing?

**Comment by voltairepunk** [comment]
@agentzh I will try to help to clarify if I may:

* Nodejs is used to make the setup of OpenResty more minimalistic. You could use anything (apache, another nginx server, another server on the same node, simple html file) as long as you are able to set test headers so you would be able to notice the issue. Anything reproduces the problem as long as the setup as defined in the example configuration files
* The extra scripts that @kipras provided we use so we could replicate the issue faster. With the provided setup, the issue can be replicated in seconds whereas the test case can be setup in basically minutes.
* The issue can always be captured either via logging the upstream IP:PORT or a possible test header that is set for each app (see the example configuration logging). In the provided configurations we use two similar webapps that contain different headers and different ports that are logged and can be checked.
* Whenever the mixed up upstream is received coming in from the 2nd layer, we can clearly see that its buffer contains data from another webapp. Everything else (request, upstream details, etc) looks to be correct. If we add a unique ID/Hash to be compared between the upstream and the request before they are sent out, they come in correctly. It is just the upstream buffer that contains incorrect data.
* In order for the problem to be reproduced, you have to "stress" the server a little so that there would be many connections to the different webapps, some of which time out, the others would succeed and return data.

**Comment by kipras** [comment]
Hey @agentzh - we've produced a simple test case for this:
```
use Test::Nginx::Socket::Lua;
use Cwd qw(cwd);

plan tests => repeat_each() * (blocks() * 4);

no_long_string();
run_tests();

__DATA__

=== TEST: upstream mixups
--- main_config
    env TEST_NGINX_SERVER_PORT;

--- config
    location /req_1 {
      content_by_lua_block {
        local up_sock = ngx.socket.tcp()
        up_sock:connect("127.0.0.1", os.getenv("TEST_NGINX_SERVER_PORT"))
        up_sock:settimeout(500)

        local uri = "/req_1_origin"

        up_sock:send(ngx.var.request_method .. " " .. uri .. " " .. ngx.var.server_protocol .. "\r\n")
        up_sock:send(ngx.req.raw_header(true))

        local down_sock = ngx.req.socket(true)
        local response = up_sock:receive("*a") or [[
200 OK
]]
        down_sock:send(response)

        up_sock:setkeepalive()
      }
    }

    location /req_1_origin {
      echo_sleep 1.000;
      echo -n "request 1";
    }

    location /req_2 {
      content_by_lua_block {
        local up_sock = ngx.socket.tcp()
        up_sock:connect("127.0.0.1", os.getenv("TEST_NGINX_SERVER_PORT"))
        up_sock:settimeout(1200)

        local uri = "/req_2_origin"

        up_sock:send(ngx.var.request_method .. " " .. uri .. " " .. ngx.var.server_protocol .. "\r\n")
        up_sock:send(ngx.req.raw_header(true))

        local down_sock = ngx.req.socket(true)
        local response = up_sock:receive("*a") or [[
200 OK
]]
        down_sock:send(response)

        up_sock:setkeepalive()
      }
    }

    location /req_2_origin {
      echo -n "request 2";
    }

--- request eval
["GET /req_1", "GET /req_2"]

--- response_body eval
["", "request 2"]
```

Here - the first request times out and then the second request gets the response of the first request.
Again - if keepalive or timeout is disabled - the issue goes away and test passes.
Also, if `ngx_http_lua_socket_tcp_finalize()` call in `ngx_http_lua_socket_handle_read_error()` is enabled - the issue also goes away.

If you have a chance to look at this - let me know your thoughts. Thanks.

**Comment by detailyang** [comment]
Hello
@kipras, i guess that it's your api usage error rather than openresty:). Let me explain to you.

![942](https://cloud.githubusercontent.com/assets/3370345/20720450/202209d0-b69a-11e6-86ac-050881fb6c8e.jpg)

when you executed ` local response = up_sock:receive("*a") or [[ 200 OK ]]`, first time it's timedout after 0.5s. And you set to keepalive to this connection, you get the same connection again in `location /req2`, then you send to `GET /req2_origin`， it's just like [HTTP_pipelining](https://en.wikipedia.org/wiki/HTTP_pipelining). you send `GET /req1_origin` and `/req2_origin`  one by one, so you will receive the first response `request 1` and second response `request 2`. But you use `up_sock:send(ngx.req.raw_header(true))` which including the header `Connection: close`, in other ways you are talking to the nginx that it's not a keepalive connection. so when nginx response `request 1`, then it will close this connection , so you cannot get the `request 2`.

it can add the one line code (reread the connection before enter the location /req2) to you test to solve you question
```bash
use Test::Nginx::Socket::Lua;
use Cwd qw(cwd);

plan tests => repeat_each() * (blocks() * 4);

no_long_string();
run_tests();

__DATA__

=== TEST: upstream mixups
--- main_config
    env TEST_NGINX_SERVER_PORT;

--- config
    location /req_1 {
      content_by_lua_block {
        local up_sock = ngx.socket.tcp()
        up_sock:connect("127.0.0.1", os.getenv("TEST_NGINX_SERVER_PORT"))
        up_sock:settimeout(500)

        local uri = "/req_1_origin"

        up_sock:send(ngx.var.request_method .. " " .. uri .. " " .. ngx.var.server_protocol .. "\r\n")
        up_sock:send(ngx.req.raw_header(true))

        local down_sock = ngx.req.socket(true)
        local response = up_sock:receive("*a") or [[
200 OK
]]
	--reread
        up_sock:receive("*a")

        down_sock:send(response)

        up_sock:setkeepalive()
      }
    }

    location /req_1_origin {
      echo_sleep 1.000;
      echo -n "request 1";
    }

    location /req_2 {
      content_by_lua_block {
        local up_sock = ngx.socket.tcp()
        up_sock:connect("127.0.0.1", os.getenv("TEST_NGINX_SERVER_PORT"))
        up_sock:settimeout(1200)

        local uri = "/req_2_origin"

        up_sock:send(ngx.var.request_method .. " " .. uri .. " " .. ngx.var.server_protocol .. "\r\n")
        up_sock:send(ngx.req.raw_header(true))

        local down_sock = ngx.req.socket(true)
        local response = up_sock:receive("*a") or [[
200 OK
]]
        down_sock:send(response)

        up_sock:setkeepalive()
      }
    }

    location /req_2_origin {
      echo -n "request 2";
    }

--- request eval
["GET /req_1", "GET /req_2"]

--- response_body eval
["", "request 2"]
```

Also i suggest that you can use tcpdump to explore this question:) (personally rename req2_origin to req3_origin for test)
![screen shot 2016-11-30 at 11 02 31](https://cloud.githubusercontent.com/assets/3370345/20738220/98187cf6-b6ec-11e6-8e48-a572ce56c619.png)

**Comment by kipras** [comment]
Thank you very much @detailyang for the detailed response.

I see what you are saying - that the response mixup happens because of this Lua code not handling HTTP pipelining properly. I think the main confusion here is the assumption that `:setkeepalive()` could be used pretty much interchageably with `:close()`, which it cannot in this case, because there is outstanding data to be read. And since :setkeepalive() does not actually close the connection -
you get that response the next time that connection is used (by picking it from the keepalive pool).

And, while i don't think there are valid use cases where you would want to send some requests (be it HTTP, redis or whatever other protocol), then close or keepalive the connection, only to read the response back once the connection is reestablished some time later - i assume that nginx/ngx_lua cannot itself drop the remaining response (that has timed out) in order to remain transparent.

So it seems that it is up to the user to either:
A) read the remaining data after a timeout occurred with another call(s) to `:receive()`, as you suggested
or
B) close (instead of keepaliving) the connection in case of a read timeout

Again, thank you for the explanation, I'm closing this ticket - we'll fix this on our side.

I would only make one suggestion (if i may) - to add some info to the docs, warning about this case (danger of outstanding read data when using timeouts with keepalive), so that other users would be aware of this. I don't think we're the only ones that could be running into this problem.

Also, looks like there's no need to do this when `ngx_http_lua_socket_tcp_finalize()` is run in `ngx_http_lua_socket_handle_read_error()`, because `ngx_http_lua_socket_tcp_finalize()` implicitly closes the connection, so `up_sock:setkeepalive()` there has no effect.
