### ISSUE TITLE
Cannot parse json from ngx.var.request_body

### ISSUE THREAD

**Issue by iamnotaprogrammer** [openresty/lua-nginx-module#925]
i have sections in my nginx config block
``` lua
 access_by_lua_block{
                        local cjson = require("cjson")
                        ngx.req.read_body()
                        local text = ngx.var.request_body
                        local value = cjson.new().decode(text)
                        ngx.say(text)
                        ngx.say(type(value))
                        ngx.say(table.getn(value))
                        for k,v in ipairs(value) do
                            ngx.say(k)
                            ngx.say(table.getn(v))
                            for _, vv in ipairs(v) do
                                ngx.say(_)
                                ngx.say(vv)
                            end
                        end

```
from command line use curl 
curl -H "Content-Type: application/json" -X POST -d '[ {"username":"xyz"},{"password":"xyz"} ]'  http://localhost:8082/json/add/
the answer
[ {"username":"xyz"}, {"password":"xyz"} ]
table
2
1
0
2
0

How can i parse json?

**Comment by agentzh** [comment]
@iamnotaprogrammer Beginner questions should go to the openresty-en mailing list instead. Thank you. See http://openresty.org/en/community.html

Regarding your question, you should use `cjson.decode(text)` instead of `cjson.new().decode(text)` I'm afraid. Also, you should use `pairs()` instead of `ipairs()` to iterate through a hash table. Better consult the Lua 5.1 reference manual for more details: http://www.lua.org/manual/5.1/manual.html

**Comment by amintabar** [comment]
Thanks @agentzh 
That's my problem too ;-)
