### ISSUE TITLE
ngx.req.read_body() 会导致 lua 侧漏吗？

### ISSUE THREAD

**Issue by dhh123** [openresty/lua-nginx-module#937]
* Tengine/2.1.2 (nginx/1.6.2)   + lua ( 0.10.6)
* luajit 2.0.2
* 代码

      content_by_lua_block {
           local reports = ngx.shared.reports
           local time_stamp = math.floor(ngx.time()/60)
           local cjson = require "cjson"
           ngx.req.read_body()
           local cip = ngx.var.remote_addr or '127.0.0.1'
           --local post_args = ngx.var.request_body
           if not ngx.var.request_body then
               ngx.log(ngx.ERR, "Got a null body")
               ngx.say(cjson.encode({['msg']="ok",['ret']=0}))
               return
           end
           local redis = require "redis"
           local red = redis:new()
           local ok,err = red:connect('xxxx',xxxx)
           if not ok then
               ngx.log(ngx.ERR, "Failed to connect: ", err)
           else
               local count, err= reports:incr(time_stamp, 1)
               if not count and err == "not found" then
                   reports:add(time_stamp,0)
                   reports:incr(time_stamp,1)
               end
           end
           local ok, err = red:rpush('XXX', ngx.var.request_body.."&ip="..cip)
           if not ok then
               ngx.log(ngx.ERR, "redis rpush error: ", err)
           end
           local pooled,err=red:set_keepalive(10000,1500)
           if not pooled then
               ngx.log(ngx.ERR, 'redis connect pool faild!',err)
           end
           ngx.say(cjson.encode({['msg']="ok",['ret']=0}))

      }
我用这个代码将用户上报的请求到redis里面，不过最近在一组上报body较大的一组机器发现都会有一两个nginx worker 的mem 和 cpu占用很高，导致lua atpanic: Lua VM crashed, reason: not enough memory ，有些机器正常。

出问题的机器存在一些异常超时的，有时候还有close_wait
[xxx@tengine05 xxxx]# curl 127.0.0.1/gc
GC: 558KB
[xxx@tengine05 xxxx]# curl 127.0.0.1/gc
GC: 111179KB
有的worker gc 很大。。求春哥支招，，是代码有问题，还是有泄漏啊

**Comment by agentzh** [comment]
@dhh123 Please, no Chinese here. This place is considered English only. If you really
want to use Chinese, please join the openresty (Chinese) mailing list instead.
Please see https://openresty.org/en/community.html Thanks for your cooperation.

Regarding your question, Tengine is not an official supported target of this module. Please use either the OpenResty bundle (highly recommended) or the stock nginx core. Your LuaJIT version is ancient and may have leaks that are already fixed in newer versions (the latest OpenResty formal release already has the well tested LuaJIT new version).
